# From Unstructured Text to Interactive Knowledge Graphs Using LLMs

**Goal:** This notebook demonstrates a **highly granular, step-by-step process** to transform raw, unstructured text into a structured, interactive knowledge graph using Large Language Models (LLMs). We will extract factual information (SPO triples) and visualize the data transformations and final graph **directly within the notebook** at multiple stages.

**Target Audience:** Beginners to Intermediate Python users interested in NLP, Knowledge Graphs, and LLMs, who want to see the data evolve at each step.

**Approach:** We will break down the process into very small, logical steps. Each step will aim to perform a distinct action, followed by an output or visualization to show the immediate result. We'll use basic Python constructs and popular libraries, prioritizing clarity and step-by-step understanding over code conciseness.

## Theory: What is a Knowledge Graph?

A Knowledge Graph (KG) is a way to represent information as a network of entities and their relationships. Think of it like a structured database, but instead of tables, you have:

*   **Nodes (or Entities):** These represent real-world objects, concepts, people, places, organizations, etc. (e.g., 'Marie Curie', 'Physics', 'Paris'). In our graph, each unique subject or object from our extracted facts will become a node.
*   **Edges (or Relationships):** These represent the connections or interactions between entities. They typically have a direction and a label describing the relationship (e.g., 'Marie Curie' -- `won` --> 'Nobel Prize', 'Radium' -- `is element discovered by` --> 'Marie Curie'). In our graph, each predicate from our extracted facts defines an edge between the corresponding subject and object nodes.

Knowledge graphs make it easier to understand complex connections, infer new information, and query data in intuitive ways. Visualizing the graph helps immensely in spotting patterns and understanding the overall structure.

## Theory: Subject-Predicate-Object (SPO) Triples

The fundamental building block of many knowledge graphs derived from text is the **Subject-Predicate-Object (SPO)** triple. It's a simple structure that captures a single fact:

*   **Subject:** The entity the statement is about (becomes a node).
*   **Predicate:** The relationship or action connecting the subject and object (becomes the label on an edge).
*   **Object:** The entity related to the subject via the predicate (becomes another node).

**Example:** "Marie Curie discovered Radium" -> (`Marie Curie`, `discovered`, `Radium`).

This translates to graph nodes and edges: `(Marie Curie) -[discovered]-> (Radium)`.

LLMs help identify these triples by understanding language context.

## Step 1: Setup - Installing Libraries

First, we install the necessary Python libraries. We'll use:
*   `openai`: For LLM API interaction.
*   `networkx`: For graph data structures.
*   `ipycytoscape`: For interactive in-notebook graph visualization.
*   `ipywidgets`: Required by `ipycytoscape`.
*   `pandas`: For displaying data nicely in tables.

**Note:** You might need to restart the runtime/kernel after installation. Enable `ipywidgets` extension in classic Jupyter Notebook if needed.

In [31]:
# Install libraries (run this cell once)
%uv sync

# If in classic Jupyter Notebook (not Lab), you might need to enable the widget extension:
# jupyter nbextension enable --py widgetsnbextension

# --- IMPORTANT: Restart the kernel/runtime after running this cell! ---

Note: you may need to restart the kernel to use updated packages.

Resolved 225 packages in 1.68s
Audited 218 packages in 1ms

## Step 2: Setup - Importing Libraries

Now that the libraries are installed, we import the necessary components into our Python environment.

In [32]:
import openai  # For LLM interaction
import json  # For parsing LLM responses
import networkx as nx  # For creating and managing the graph data structure
import ipycytoscape  # For interactive in-notebook graph visualization
import pandas as pd  # For displaying data in tables
import os  # For accessing environment variables (safer for API keys)
import re  # For basic text cleaning (regular expressions)
import warnings  # To suppress potential deprecation warnings

# Configure settings for better display and fewer warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
pd.set_option("display.max_rows", 100)  # Show more rows in pandas tables
pd.set_option("display.max_colwidth", 150)  # Show more text width in pandas tables

print("Libraries imported successfully.")

Libraries imported successfully.

## Step 3: Configure LLM Access

We need to specify how to connect to the Large Language Model. This involves the API endpoint (URL) and the API key.

**IMPORTANT SECURITY NOTE:** Use environment variables or a secure secrets manager for API keys. **Do not hardcode keys directly in the notebook.**

**Environment Variable Setup (Example - run in your terminal *before* starting Jupyter):**
```bash
# For OpenAI
export OPENAI_API_KEY='your_openai_api_key'

# For Ollama (example)
export OPENAI_API_KEY='ollama' # Or any non-empty string
export OPENAI_API_BASE='http://localhost:11434/v1'

# For Nebius AI (example)
export OPENAI_API_KEY='your_nebius_api_key'
export OPENAI_API_BASE='https://api.studio.nebius.com/v1/'
```
First, we'll define the model name we intend to use.

In [ ]:
# --- Retrieve Credentials ---
from dotenv import load_dotenv

# 加载 .env 文件
load_dotenv()
api_key = os.getenv("LLM_API_KEY")
base_url = os.getenv(
    "LLM_BASE_URL"
)  # Will be None if not set (e.g., for standard OpenAI)
llm_model_name = os.getenv("KG_LLM_MODEL_NAME")

print(f"Intended LLM model: {llm_model_name}")

Intended LLM model: gemini-1.5-flash

Now, let's retrieve the API key and base URL from environment variables.

In [34]:
# --- FOR TESTING ONLY (Less Secure - Replace with Environment Variables) ---
# Uncomment and set these lines ONLY if you cannot set environment variables easily.
# api_key = "YOUR_API_KEY_HERE"  # <--- PASTE KEY HERE FOR TESTING ONLY
# base_url = "YOUR_API_BASE_URL_HERE" # <--- PASTE BASE URL HERE (if needed)
# Example for Nebius:
# base_url="https://api.studio.nebius.com/v1/"
# api_key="YOUR_NEBIUS_KEY"

print(f"Retrieved API Key: {'Set' if api_key else 'Not Set'}")
print(
    f"Retrieved Base URL: {base_url if base_url else 'Not Set (will use default OpenAI)'}"
)

Retrieved API Key: Set
Retrieved Base URL: https://xiaoai.plus/v1

Next, we validate the API key and initialize the `openai` client.

In [35]:
# --- Validate Key and Initialize Client ---
if not api_key:
    print(
        "Error: OPENAI_API_KEY environment variable not set or key not provided directly."
    )
    print(
        "Please set the environment variable (or uncomment/edit the test lines) and restart the kernel."
    )
    raise SystemExit("API Key configuration failed.")
else:
    try:
        client = openai.OpenAI(
            base_url=base_url,  # Pass None if not set, client handles default
            api_key=api_key,
        )
        print("OpenAI client initialized successfully.")
    except Exception as e:
        print(f"Error initializing OpenAI client: {e}")
        print("Check your API key, base URL (if used), and network connection.")
        raise SystemExit("LLM client initialization failed.")

OpenAI client initialized successfully.

Finally, let's define other LLM parameters like temperature and max tokens.

In [36]:
# --- Define LLM Call Parameters ---
llm_temperature = 0.0  # Lower temperature for more deterministic, factual output. 0.0 is best for extraction.
llm_max_tokens = 4096  # Max tokens for the LLM response (adjust based on model limits)

print(f"LLM Temperature set to: {llm_temperature}")
print(f"LLM Max Tokens set to: {llm_max_tokens}")

LLM Temperature set to: 0.0
LLM Max Tokens set to: 4096

## Step 4: Define Input Text

Here, we define the raw, unstructured text we want to process. We'll use the Marie Curie biography.

In [37]:
import os


def read_md_files_to_string(directory):
    """
    Recursively reads all .md files in the given directory and its subdirectories,
    concatenates their content into a single string, and prefixes each file's content
    with its filename.

    Args:
        directory (str): The root directory to start reading .md files.

    Returns:
        str: A single string containing the content of all .md files.
    """
    combined_text = ""

    for root, _, files in os.walk(directory):
        for file in files:
            print(file)
            if file.endswith(".md") or file.endswith(".txt"):
                file_path = os.path.join(root, file)
                try:
                    with open(file_path, "r", encoding="utf-8") as f:
                        file_content = f.read()
                        combined_text += f"--- File: {file} ---\n{file_content}\n\n"
                except Exception as e:
                    print(f"Error reading file {file_path}: {e}")

    return combined_text


# Example usage
directory_path = "../../data/local/"  # Replace with your target directory
unstructured_text = read_md_files_to_string(directory_path)
print("All .md files have been read and combined into unstructured_text.")
print(unstructured_text)

animal.txt
.meta.json
.meta.json
.meta.json
.meta.json
.meta.json
.meta.json
.meta.json
.meta.json
.meta.json
.meta.json
.meta.json
cat.txt
dog.txt
fox.txt
ham.txt
owl.txt
parrot.txt
wolf.txt
All .md files have been read and combined into unstructured_text.
--- File: animal.txt ---
动物是地球上生物多样性的重要组成部分。它们与植物、微生物共同构成了复杂的生态系统，维持着地球的生态平衡。在我看来，动物不仅仅是自然界的一部分，它们还有着丰富的内涵和意义。

首先，动物是大自然的奇迹。地球上的动物种类繁多，从微小的昆虫到巨大的蓝鲸，每一种动物都有其独特的生存方式和适应策略。昆虫以其惊人的数量和多样性占据了地球的每一个角落，而大象等大型动物则以其体型和力量令人惊叹。每种动物都通过进化发展出适应其生存环境的独特特征，这显示了生命的无比奇妙和顽强。

其次，动物与人类有着密切的关系。很多动物与人类共同生活，扮演着朋友、助手或工作伙伴的角色。宠物如猫狗，给予了人类无尽的陪伴和情感支持；而一些工作动物如导盲犬、缉毒犬等，帮助人类完成某些特殊任务。同时，动物在农业和科研中也扮演着重要角色，家畜和家禽为人类提供食物来源，而实验动物则是科学研究的重要对象。

然而，人类活动对动物的影响不容忽视。工业化进程、城市化扩张、森林砍伐等都威胁着动物的栖息地，导致许多物种濒临灭绝。偷猎和非法贸易则进一步加剧了某些物种的生存危机。为此，各国政府和国际组织不断加强动物保护法律法规，推动拯救濒危动物的努力。

此外，动物在文化和精神层面也占有重要地位。许多文化中，动物被视为神灵的化身或图腾，承载着丰厚的历史和信仰。在文学作品、电影和艺术中，动物角色时常被用来表现人类无法用语言表达的情感和哲理。

总之，动物是自然界的珍宝，也是人类的朋友和老师。保护动物及其生存环境，不仅是在保护我们的生态系统，也是在保护人类自身的未来。通过尊重和理解动物，我们能够与自然和谐相处，共同迎接更美好的未来。

--- File: cat.txt ---
猫是一种常见的宠物，以其温顺和独立性闻名。它们通常有柔软的毛发、敏锐的感官以及敏捷的动作。猫可以很好地适应各种居住环境，它们的呼噜声常被认为具有舒缓和疗愈作用。

--- File: dog.txt ---
狗是人类的宠物，是人类最好的朋友之一，忠诚、友好且常常充满活力。它们通常能够提供陪伴、保护家庭，并且可以通过训练来进行各种工作，如导盲、救援和警戒。狗有很多品种，每种都有自己独特的特性和需求。无论是作为家庭宠物还是工作伙伴，狗都在人们的生活中扮演着重要角色。

--- File: fox.txt ---
狐狸是一种小型哺乳动物，属于犬科动物。它们通常以聪明、狡猾而闻名。狐狸的身体结构优雅，体型较小，通常具有尖尖的鼻子和大耳朵，这些适应性特征使狐狸在觅食时特别灵敏。狐狸的皮毛多为红色，但也有灰色、银色、甚至白色变种。在一些文化中，狐狸往往被赋予智慧和狡黠的象征意义。

首先，狐狸有着非常敏锐的嗅觉和听觉，这使得它们能够在复杂的环境中有效地追踪猎物。它们主要以小型哺乳动物、鸟类以及昆虫为食，有时也会吃植物果实。此外，狡猾的进食策略使得狐狸能够在食物稀缺的季节有效地获取营养。

狐狸的社交结构相对简单。通常情况下，狐狸是独居动物，仅在繁殖季节与其他狐狸交往。它们会建立自己的领地，并通过标记信息来维持领地的独占性。母狐狸通常在隐蔽的巢穴中产仔，并抚养幼崽直至其具备独立生活能力。

在文化历史中，狐狸常被赋予不同的角色。例如，狐狸在中国民间传说中有时被看作是善于变化和狡黠的化身。类似地，在西方故事中，狐狸也常被刻画成一种聪明的形象，能够运用智谋解决麻烦。在许多寓言和故事中，狐狸角色往往通过诡计来实现其目标，这种描绘尽显其狡猾的一面。

尽管狐狸有时被视为破坏庄稼和袭击家畜的害兽，人们逐渐认识到它们在生态系统中扮演着重要角色。狐狸通过捕食啮齿动物帮助控制其数量，从而减少农作物的损害。有时，它们还作为较大食肉动物的猎物，成为食物链的一部分。

人们对于狐狸的态度也随着时间的推移而改变。在过去，狐狸皮曾被广泛使用于毛皮工业，但由于动物保护意识的提高，野生狐狸的生存状态得到了更大关注。在现代社会，狐狸不仅是生态系统的重要组成部分，也成为了一些地区保护生态平衡的重要对象。

总的来说，狐狸是一种极具适应能力的动物。它们通过聪明和灵活的行为在不同的环境中求得生存，成为自然界一种特殊的存在。狐狸令人敬畏的智慧和偶尔显露的狡黠，使它们成为具有人格化特征的动物。在保护自然和动物的呼声愈发高涨的今天，狐狸的形象也愈发丰富和立体。狐狸不仅是自然界的精灵，也成为激发人们创造灵感的源泉。狐狸的故事和传说将继续流传，成为人类文化的一部分。这种生物的魅力深入人心，不论是在文学作品中，还是在日常生活的观念里，狐狸的名声和象征意义都得到了广泛认可。

--- File: ham.txt ---
仓鼠是一种小型啮齿动物，属于仓鼠科。它们通常体型娇小，外形可爱，深受人们的喜爱，许多人选择把仓鼠作为宠物来饲养。仓鼠在大自然中主要分布在亚洲、欧洲及北美洲地区，其中以中国、俄罗斯和哈萨克斯坦等地较为常见。

仓鼠的种类繁多，最常见的包括：金丝熊、坎贝尔仓鼠、加卡利亚仓鼠和罗伯罗夫斯基仓鼠等。每种仓鼠都有自己独特的特征，例如金丝熊仓鼠体型较大，性格温顺，而加卡利亚仓鼠则体型较小，活泼好动。

仓鼠生活在各种环境中，它们既可以在野外生存，也能够适应人工饲养的环境。野生仓鼠通常栖息在沙漠、草原地带，那里可以提供充足的食物和庇护所。仓鼠是夜行动物，白天通常躲在洞穴中，晚上出来觅食、活动。

仓鼠的饮食以植物为主，主要包括各种种子、果实、坚果、谷物等，偶尔也会吃一些昆虫和小型动物。这种饮食习惯使它们能够有效储存食物，以应对食物匮乏的时刻。仓鼠天生具备将食物储存在颊囊中的能力，在觅食时常常把食物塞满颊囊，然后带回巢穴慢慢享用。

在人工饲养环境中，仓鼠需要提供足够的空间来活动和居住，常用的笼子应足够宽敞，并配备跑轮、隧道、栖息的木屋和适合磨牙的玩具，以满足仓鼠的运动和磨牙需求。同时，饮水和食物则需要每天提供和更换，以保持仓鼠的健康。

仓鼠是一种相对独立的动物，通常喜欢独居，因此在饲养过程中尽量避免将多只仓鼠放在一起，以防止打斗。此外，仓鼠比较容易受到惊吓，应减少惊动仓鼠的次数，并进行温柔的互动。

饲养仓鼠还有一个重要环节就是注意卫生，定期清理仓鼠的居住环境，去除粪便和污垢，以防止细菌滋生造成疾病。还需要注意观察仓鼠的身体状况，如发现异常应及时咨询兽医。

养仓鼠不仅可以带来愉悦感，还能学到许多知识，如通过观察仓鼠的行为和习惯，了解动物的生态和生活规律。同时，饲养仓鼠也教育了人们关于责任心和耐心的重要性，因为照料小动物是一个长期的承诺，需要用心投入。

总之，仓鼠是一种可爱的动物，适合家庭饲养，但前提是要了解它们的习性，并确保提供适合的居住环境和饮食条件。只有这样，才能够让仓鼠快乐地生活，给主人带来无限乐趣。

--- File: owl.txt ---
猫头鹰是一种夜行性猛禽，以其独特的外表和习性著称。它们的大眼睛和圆脸盘让它们具有极高的视觉和听觉能力，适合在夜间狩猎。猫头鹰的羽毛结构特别，有助于无声飞行。此外，它们可以旋转头部约270度，以弥补眼球不能转动的不足。猫头鹰在文化中常被视为智慧的象征。

--- File: parrot.txt ---
鹦鹉是一种美丽而聪明的鸟类，因其能够模仿人类语言和声音而闻名。它们具有鲜艳的羽毛，通常呈现绿色、蓝色、红色等颜色。鹦鹉的智力较高，可以学习一些简单的指令和进行复杂的社交互动。它们通常以种子、坚果和水果为食，是群居动物，通常生活在热带和亚热带地区的森林中。鹦鹉也是人类的宠物。作为宠物，鹦鹉需要大量的社交时间和适当的环境刺激，以保持健康和快乐。

--- File: wolf.txt ---
狼是一种极具智慧和社会性的动物，属于犬科，是一种野生哺乳动物。狼通常生活在群体中，以群体合作的方式进行猎食，这种社会组织使得狼能够在复杂的自然环境中生存下来。狼群通常由一个或几个核心家庭组成，狼群中有明确的等级制度，通常由一对主导的成年狼负责领导和保护群体。

狼在自然生态系统中扮演着重要的角色，它是顶级捕食者之一，主要猎食草食性动物，如鹿、麋鹿、野牛等。通过猎食活动，狼可以帮助控制猎物种群的数量，从而维持生态系统的平衡。狼以其敏锐的感官和强大的追踪能力闻名，它们有着卓越的听觉和嗅觉，这使得它们能够远距离定位猎物并制定有效的捕猎战略。

狼的交流方式多种多样，它们通过嚎叫、肢体语言、面部表情以及气味来进行沟通。狼嚎叫是最具代表性的，通常用于标识领地、召唤同伴或警告敌人。嚎叫不仅限于声音的表达，也可能包含特定的信息，例如狼群的规模和位置。肢体语言和面部表情主要用于狼群内部的交流，帮助维护群体的秩序和值得信赖的社会关系。

狼的繁殖行为十分复杂，通常一年繁殖一次。狼群一般只允许一个主导的交配对进行繁殖，这确保了群体资源能够充分支持幼狼的成长。幼狼诞生后，整个狼群都会参与照料和保护幼狼，直到它们能够独立生存。狼的幼崽通常在约六个月大时开始跟随成年狼一起猎食，并逐渐学习生存技能。

由于人类活动的扩展，狼的生存环境面临诸多挑战。过去几个世纪以来，狼的数量因人类的猎杀和栖息地的破坏而骤减。然而，随着保护意识的增强和生态保护措施的实施，狼的数量在一些地区得到恢复。保护狼不仅仅是保护一个物种，更是保护生态系统的完整性，因为狼对生态链的健康至关重要。

狼在文化中经常被赋予各种象征意义。在一些文化中，狼被视为勇敢和自由的象征，而在另一些文化中，狼可能被视为危险和狡猾的化身。如今，狼还被用于研究有关行为学和群体动力学的科学研究，这为人类了解社会结构和沟通模式提供了有价值的参考。

总的来说，狼是一种令人敬畏的生物。在自然界中，凭借其卓越的生存技巧和强大的组织能力，狼不仅在其生态角色中扮演着重要角色，也在促进生物多样性和生态稳定性方面发挥着关键作用。人类在享受和利用自然资源的同时，保护狼以及它们的栖息地变得尤为重要。这不仅能维持生态系统的健康发展，也能确保自然界中这种神秘而迷人的动物能够继续发挥其作用。

Let's display the input text and some basic statistics about it.

In [38]:
print("--- Input Text Loaded ---")
print(unstructured_text)
print("-" * 25)
# Basic stats visualization
char_count = len(unstructured_text)
word_count = len(unstructured_text.split())
print(f"Total characters: {char_count}")
print(f"Approximate word count: {word_count}")
print("-" * 25)

--- Input Text Loaded ---
--- File: animal.txt ---
动物是地球上生物多样性的重要组成部分。它们与植物、微生物共同构成了复杂的生态系统，维持着地球的生态平衡。在我看来，动物不仅仅是自然界的一部分，它们还有着丰富的内涵和意义。

首先，动物是大自然的奇迹。地球上的动物种类繁多，从微小的昆虫到巨大的蓝鲸，每一种动物都有其独特的生存方式和适应策略。昆虫以其惊人的数量和多样性占据了地球的每一个角落，而大象等大型动物则以其体型和力量令人惊叹。每种动物都通过进化发展出适应其生存环境的独特特征，这显示了生命的无比奇妙和顽强。

其次，动物与人类有着密切的关系。很多动物与人类共同生活，扮演着朋友、助手或工作伙伴的角色。宠物如猫狗，给予了人类无尽的陪伴和情感支持；而一些工作动物如导盲犬、缉毒犬等，帮助人类完成某些特殊任务。同时，动物在农业和科研中也扮演着重要角色，家畜和家禽为人类提供食物来源，而实验动物则是科学研究的重要对象。

然而，人类活动对动物的影响不容忽视。工业化进程、城市化扩张、森林砍伐等都威胁着动物的栖息地，导致许多物种濒临灭绝。偷猎和非法贸易则进一步加剧了某些物种的生存危机。为此，各国政府和国际组织不断加强动物保护法律法规，推动拯救濒危动物的努力。

此外，动物在文化和精神层面也占有重要地位。许多文化中，动物被视为神灵的化身或图腾，承载着丰厚的历史和信仰。在文学作品、电影和艺术中，动物角色时常被用来表现人类无法用语言表达的情感和哲理。

总之，动物是自然界的珍宝，也是人类的朋友和老师。保护动物及其生存环境，不仅是在保护我们的生态系统，也是在保护人类自身的未来。通过尊重和理解动物，我们能够与自然和谐相处，共同迎接更美好的未来。

--- File: cat.txt ---
猫是一种常见的宠物，以其温顺和独立性闻名。它们通常有柔软的毛发、敏锐的感官以及敏捷的动作。猫可以很好地适应各种居住环境，它们的呼噜声常被认为具有舒缓和疗愈作用。

--- File: dog.txt ---
狗是人类的宠物，是人类最好的朋友之一，忠诚、友好且常常充满活力。它们通常能够提供陪伴、保护家庭，并且可以通过训练来进行各种工作，如导盲、救援和警戒。狗有很多品种，每种都有自己独特的特性和需求。无论是作为家庭宠物还是工作伙伴，狗都在人们的生活中扮演着重要角色。

--- File: fox.txt ---
狐狸是一种小型哺乳动物，属于犬科动物。它们通常以聪明、狡猾而闻名。狐狸的身体结构优雅，体型较小，通常具有尖尖的鼻子和大耳朵，这些适应性特征使狐狸在觅食时特别灵敏。狐狸的皮毛多为红色，但也有灰色、银色、甚至白色变种。在一些文化中，狐狸往往被赋予智慧和狡黠的象征意义。

首先，狐狸有着非常敏锐的嗅觉和听觉，这使得它们能够在复杂的环境中有效地追踪猎物。它们主要以小型哺乳动物、鸟类以及昆虫为食，有时也会吃植物果实。此外，狡猾的进食策略使得狐狸能够在食物稀缺的季节有效地获取营养。

狐狸的社交结构相对简单。通常情况下，狐狸是独居动物，仅在繁殖季节与其他狐狸交往。它们会建立自己的领地，并通过标记信息来维持领地的独占性。母狐狸通常在隐蔽的巢穴中产仔，并抚养幼崽直至其具备独立生活能力。

在文化历史中，狐狸常被赋予不同的角色。例如，狐狸在中国民间传说中有时被看作是善于变化和狡黠的化身。类似地，在西方故事中，狐狸也常被刻画成一种聪明的形象，能够运用智谋解决麻烦。在许多寓言和故事中，狐狸角色往往通过诡计来实现其目标，这种描绘尽显其狡猾的一面。

尽管狐狸有时被视为破坏庄稼和袭击家畜的害兽，人们逐渐认识到它们在生态系统中扮演着重要角色。狐狸通过捕食啮齿动物帮助控制其数量，从而减少农作物的损害。有时，它们还作为较大食肉动物的猎物，成为食物链的一部分。

人们对于狐狸的态度也随着时间的推移而改变。在过去，狐狸皮曾被广泛使用于毛皮工业，但由于动物保护意识的提高，野生狐狸的生存状态得到了更大关注。在现代社会，狐狸不仅是生态系统的重要组成部分，也成为了一些地区保护生态平衡的重要对象。

总的来说，狐狸是一种极具适应能力的动物。它们通过聪明和灵活的行为在不同的环境中求得生存，成为自然界一种特殊的存在。狐狸令人敬畏的智慧和偶尔显露的狡黠，使它们成为具有人格化特征的动物。在保护自然和动物的呼声愈发高涨的今天，狐狸的形象也愈发丰富和立体。狐狸不仅是自然界的精灵，也成为激发人们创造灵感的源泉。狐狸的故事和传说将继续流传，成为人类文化的一部分。这种生物的魅力深入人心，不论是在文学作品中，还是在日常生活的观念里，狐狸的名声和象征意义都得到了广泛认可。

--- File: ham.txt ---
仓鼠是一种小型啮齿动物，属于仓鼠科。它们通常体型娇小，外形可爱，深受人们的喜爱，许多人选择把仓鼠作为宠物来饲养。仓鼠在大自然中主要分布在亚洲、欧洲及北美洲地区，其中以中国、俄罗斯和哈萨克斯坦等地较为常见。

仓鼠的种类繁多，最常见的包括：金丝熊、坎贝尔仓鼠、加卡利亚仓鼠和罗伯罗夫斯基仓鼠等。每种仓鼠都有自己独特的特征，例如金丝熊仓鼠体型较大，性格温顺，而加卡利亚仓鼠则体型较小，活泼好动。

仓鼠生活在各种环境中，它们既可以在野外生存，也能够适应人工饲养的环境。野生仓鼠通常栖息在沙漠、草原地带，那里可以提供充足的食物和庇护所。仓鼠是夜行动物，白天通常躲在洞穴中，晚上出来觅食、活动。

仓鼠的饮食以植物为主，主要包括各种种子、果实、坚果、谷物等，偶尔也会吃一些昆虫和小型动物。这种饮食习惯使它们能够有效储存食物，以应对食物匮乏的时刻。仓鼠天生具备将食物储存在颊囊中的能力，在觅食时常常把食物塞满颊囊，然后带回巢穴慢慢享用。

在人工饲养环境中，仓鼠需要提供足够的空间来活动和居住，常用的笼子应足够宽敞，并配备跑轮、隧道、栖息的木屋和适合磨牙的玩具，以满足仓鼠的运动和磨牙需求。同时，饮水和食物则需要每天提供和更换，以保持仓鼠的健康。

仓鼠是一种相对独立的动物，通常喜欢独居，因此在饲养过程中尽量避免将多只仓鼠放在一起，以防止打斗。此外，仓鼠比较容易受到惊吓，应减少惊动仓鼠的次数，并进行温柔的互动。

饲养仓鼠还有一个重要环节就是注意卫生，定期清理仓鼠的居住环境，去除粪便和污垢，以防止细菌滋生造成疾病。还需要注意观察仓鼠的身体状况，如发现异常应及时咨询兽医。

养仓鼠不仅可以带来愉悦感，还能学到许多知识，如通过观察仓鼠的行为和习惯，了解动物的生态和生活规律。同时，饲养仓鼠也教育了人们关于责任心和耐心的重要性，因为照料小动物是一个长期的承诺，需要用心投入。

总之，仓鼠是一种可爱的动物，适合家庭饲养，但前提是要了解它们的习性，并确保提供适合的居住环境和饮食条件。只有这样，才能够让仓鼠快乐地生活，给主人带来无限乐趣。

--- File: owl.txt ---
猫头鹰是一种夜行性猛禽，以其独特的外表和习性著称。它们的大眼睛和圆脸盘让它们具有极高的视觉和听觉能力，适合在夜间狩猎。猫头鹰的羽毛结构特别，有助于无声飞行。此外，它们可以旋转头部约270度，以弥补眼球不能转动的不足。猫头鹰在文化中常被视为智慧的象征。

--- File: parrot.txt ---
鹦鹉是一种美丽而聪明的鸟类，因其能够模仿人类语言和声音而闻名。它们具有鲜艳的羽毛，通常呈现绿色、蓝色、红色等颜色。鹦鹉的智力较高，可以学习一些简单的指令和进行复杂的社交互动。它们通常以种子、坚果和水果为食，是群居动物，通常生活在热带和亚热带地区的森林中。鹦鹉也是人类的宠物。作为宠物，鹦鹉需要大量的社交时间和适当的环境刺激，以保持健康和快乐。

--- File: wolf.txt ---
狼是一种极具智慧和社会性的动物，属于犬科，是一种野生哺乳动物。狼通常生活在群体中，以群体合作的方式进行猎食，这种社会组织使得狼能够在复杂的自然环境中生存下来。狼群通常由一个或几个核心家庭组成，狼群中有明确的等级制度，通常由一对主导的成年狼负责领导和保护群体。

狼在自然生态系统中扮演着重要的角色，它是顶级捕食者之一，主要猎食草食性动物，如鹿、麋鹿、野牛等。通过猎食活动，狼可以帮助控制猎物种群的数量，从而维持生态系统的平衡。狼以其敏锐的感官和强大的追踪能力闻名，它们有着卓越的听觉和嗅觉，这使得它们能够远距离定位猎物并制定有效的捕猎战略。

狼的交流方式多种多样，它们通过嚎叫、肢体语言、面部表情以及气味来进行沟通。狼嚎叫是最具代表性的，通常用于标识领地、召唤同伴或警告敌人。嚎叫不仅限于声音的表达，也可能包含特定的信息，例如狼群的规模和位置。肢体语言和面部表情主要用于狼群内部的交流，帮助维护群体的秩序和值得信赖的社会关系。

狼的繁殖行为十分复杂，通常一年繁殖一次。狼群一般只允许一个主导的交配对进行繁殖，这确保了群体资源能够充分支持幼狼的成长。幼狼诞生后，整个狼群都会参与照料和保护幼狼，直到它们能够独立生存。狼的幼崽通常在约六个月大时开始跟随成年狼一起猎食，并逐渐学习生存技能。

由于人类活动的扩展，狼的生存环境面临诸多挑战。过去几个世纪以来，狼的数量因人类的猎杀和栖息地的破坏而骤减。然而，随着保护意识的增强和生态保护措施的实施，狼的数量在一些地区得到恢复。保护狼不仅仅是保护一个物种，更是保护生态系统的完整性，因为狼对生态链的健康至关重要。

狼在文化中经常被赋予各种象征意义。在一些文化中，狼被视为勇敢和自由的象征，而在另一些文化中，狼可能被视为危险和狡猾的化身。如今，狼还被用于研究有关行为学和群体动力学的科学研究，这为人类了解社会结构和沟通模式提供了有价值的参考。

总的来说，狼是一种令人敬畏的生物。在自然界中，凭借其卓越的生存技巧和强大的组织能力，狼不仅在其生态角色中扮演着重要角色，也在促进生物多样性和生态稳定性方面发挥着关键作用。人类在享受和利用自然资源的同时，保护狼以及它们的栖息地变得尤为重要。这不仅能维持生态系统的健康发展，也能确保自然界中这种神秘而迷人的动物能够继续发挥其作用。


-------------------------
Total characters: 4139
Approximate word count: 65
-------------------------

## Step 5: Text Chunking (Optional but Recommended)

LLMs have context limits. For longer texts, we need to break them into smaller chunks. We'll define the chunk size and overlap.

*   **Chunk Size:** Max words per chunk.
*   **Overlap:** Words shared between consecutive chunks to preserve context.

In [39]:
# --- Chunking Configuration ---
chunk_size = 300  # Number of words per chunk (adjust as needed)
overlap = 30  # Number of words to overlap (must be < chunk_size)

print(f"Chunk Size set to: {chunk_size} words")
print(f"Overlap set to: {overlap} words")

# --- Basic Validation ---
if overlap >= chunk_size and chunk_size > 0:
    print(f"Error: Overlap ({overlap}) must be smaller than chunk size ({chunk_size}).")
    raise SystemExit("Chunking configuration error.")
else:
    print("Chunking configuration is valid.")

Chunk Size set to: 300 words
Overlap set to: 30 words
Chunking configuration is valid.

First, let's split the input text into a list of words.

In [40]:
import jieba

words = list(jieba.cut(unstructured_text))
total_words = len(words)

print(f"Text split into {total_words} words.")
# Visualize the first 20 words
print(f"First 20 words: {words[:20]}")

Text split into 2474 words.
First 20 words: ['---', ' ', 'File', ':', ' ', 'animal', '.', 'txt', ' ', '---', '\n', '动物', '是', '地球', '上', '生物', '多样性', '的', '重要', '组成部分']

Now, we'll perform the chunking based on the configuration.

In [41]:
chunks = []
start_index = 0
chunk_number = 1

print("Starting chunking process...")

while start_index < total_words:
    end_index = min(start_index + chunk_size, total_words)
    chunk_text = " ".join(words[start_index:end_index])
    chunks.append({"text": chunk_text, "chunk_number": chunk_number})

    # print(f"  Created chunk {chunk_number}: words {start_index} to {end_index-1}") # Uncomment for detailed log

    # Calculate the start of the next chunk
    next_start_index = start_index + chunk_size - overlap

    # Ensure progress is made
    if next_start_index <= start_index:
        if end_index == total_words:
            break  # Already processed the last part
        next_start_index = start_index + 1

    start_index = next_start_index
    chunk_number += 1

    # Safety break (optional)
    if chunk_number > total_words:  # Simple safety
        print("Warning: Chunking loop exceeded total word count, breaking.")
        break

print(f"\nText successfully split into {len(chunks)} chunks.")

Starting chunking process...

Text successfully split into 10 chunks.

Let's visualize the created chunks using Pandas DataFrame.

In [42]:
print("--- Chunk Details ---")
if chunks:
    # Create a DataFrame for better visualization
    chunks_df = pd.DataFrame(chunks)
    chunks_df["word_count"] = chunks_df["text"].apply(lambda x: len(x.split()))
    display(chunks_df[["chunk_number", "word_count", "text"]])
else:
    print("No chunks were created (text might be shorter than chunk size).")
print("-" * 25)

--- Chunk Details ---

,chunk_number,word_count,text
0,1,290,--- File : animal . txt --- \n 动物 是 地球 上 生物 多样性 的 重要 组成部分 。 它们 与 植物 、 微生物 共同 构成 了 复杂 的 生态系统 ， 维持 着 地球 的 生态平衡 。 在我看来 ， 动物 不仅仅 是 自然界 的 一部分 ， 它...
1,2,284,导致 许多 物种 濒临灭绝 。 偷猎 和 非法 贸易 则 进一步 加剧 了 某些 物种 的 生存 危机 。 为此 ， 各国 政府 和 国际 组织 不断加强 动物 保护 法律法规 ， 推动 拯救 濒危动物 的 努力 。 \n \n 此外 ， 动物 在 文化 和 精神 层面 也 占有 重要 地位...
2,3,288,， 如导盲 、 救援 和 警戒 。 狗 有 很多 品种 ， 每种 都 有 自己 独特 的 特性 和 需求 。 无论是 作为 家庭 宠物 还是 工作 伙伴 ， 狗 都 在 人们 的 生活 中 扮演着 重要 角色 。 \n \n --- File : fox . txt --- \n...
3,4,294,狐狸 常 被 赋予 不同 的 角色 。 例如 ， 狐狸 在 中国 民间传说 中 有时 被 看作 是 善于 变化 和 狡黠 的 化身 。 类似 地 ， 在 西方 故事 中 ， 狐狸 也 常 被 刻画 成 一种 聪明 的 形象 ， 能够 运用 智谋 解决 麻烦 。 在 许多 寓言 和 故事 中 ...
4,5,288,愈发 丰富 和 立体 。 狐狸 不仅 是 自然界 的 精灵 ， 也 成为 激发 人们 创造 灵感 的 源泉 。 狐狸 的 故事 和 传说 将 继续 流传 ， 成为 人类 文化 的 一部分 。 这种 生物 的 魅力 深入人心 ， 不论是 在 文学作品 中 ， 还是 在 日常生活 的 观念 里 ...
5,6,290,、 坚果 、 谷物 等 ， 偶尔 也 会 吃 一些 昆虫 和 小型 动物 。 这种 饮食习惯 使 它们 能够 有效 储存 食物 ， 以 应对 食物 匮乏 的 时刻 。 仓鼠 天生 具备 将 食物 储存 在 颊囊 中 的 能力 ， 在 觅食 时 常常 把 食物 塞满 颊囊 ， 然后 带回 巢穴...
6,7,280,因为 照料 小 动物 是 一个 长期 的 承诺 ， 需要 用心 投入 。 \n \n 总之 ， 仓鼠 是 一种 可爱 的 动物 ， 适合 家庭 饲养 ， 但 前提 是 要 了解 它们 的 习性 ， 并 确保 提供 适合 的 居住 环境 和 饮食 条件 。 只有 这样 ， 才 能够 让 仓鼠 ...
7,8,288,健康 和 快乐 。 \n \n --- File : wolf . txt --- \n 狼 是 一种 极具 智慧 和 社会性 的 动物 ， 属于 犬科 ， 是 一种 野生 哺乳动物 。 狼 通常 生活 在 群体 中 ， 以 群体 合作 的 方式 进行 猎食 ， 这种 社会 组织...
8,9,294,一次 。 狼群 一般 只 允许 一个 主导 的 交配 对 进行 繁殖 ， 这 确保 了 群体 资源 能够 充分 支持 幼狼 的 成长 。 幼狼 诞生 后 ， 整个 狼群 都 会 参与 照料 和 保护 幼狼 ， 直到 它们 能够 独立 生存 。 狼 的 幼崽 通常 在 约 六个月 大时 开始 ...
9,10,42,享受 和 利用 自然资源 的 同时 ， 保护 狼 以及 它们 的 栖息地 变得 尤为重要 。 这 不仅 能 维持 生态系统 的 健康 发展 ， 也 能 确保 自然界 中 这种 神秘 而 迷人 的 动物 能够 继续 发挥 其 作用 。 \n \n

-------------------------

## Step 6: Define the LLM Prompt for Extraction

This is a critical step. We need to carefully instruct the LLM to extract SPO triples in a specific JSON format. We'll define a system prompt (role) and a user prompt template (instructions).

**Key Instructions Emphasized:**
*   Extract `Subject-Predicate-Object` triples.
*   Output *only* a valid JSON array of objects.
*   Each object must have `"subject"`, `"predicate"`, `"object"` keys.
*   Predicates should be concise (1-3 words).
*   All output values must be lowercase.
*   Resolve pronouns to specific entity names.
*   No extra text, explanations, or markdown code fences around the JSON.

In [43]:
# --- System Prompt: Sets the context/role for the LLM ---
extraction_system_prompt = """
你是一位处理知识图谱提取的 AI 专家。我将用英文给出 Prompt，但你需要对处理文本中的语言保持原样，即不必翻译为英文后输出。
You are an AI expert specialized in knowledge graph extraction. 
Your task is to identify and extract factual Subject-Predicate-Object (SPO) triples from the given text.
Focus on accuracy and adhere strictly to the JSON output format requested in the user prompt.
Extract core entities and the most direct relationship.
"""

# --- User Prompt Template: Contains specific instructions and the text ---
extraction_user_prompt_template = """
Please extract Subject-Predicate-Object (S-P-O) triples from the text below. 对于文本中的名词、关系，如果原文使用中文表述，你生成的内容也应该为中文；即：不必将内容翻译为英文再输出。

如果节点和关系中出现用 $$ 括起来的公式，你需要将公式表达为不含 $$ 的文本形式，不使用 latex 语法，不必严谨表述，只要能大致看出公式形式即可。

**VERY IMPORTANT RULES:**
1.  **Output Format:** Respond ONLY with a single, valid JSON array. Each element MUST be an object with keys "subject", "predicate", "object".
2.  **JSON Only:** Do NOT include any text before or after the JSON array (e.g., no 'Here is the JSON:' or explanations). Do NOT use markdown ```json ... ``` tags.
3.  **Concise Predicates:** Keep the 'predicate' value concise (1-3 words, ideally 1-2). Use verbs or short verb phrases (e.g., 'discovered', 'was born in', 'won').
4.  **Lowercase:** ALL values for 'subject', 'predicate', and 'object' MUST be lowercase.
5.  **Pronoun Resolution:** Replace pronouns (she, he, it, her, etc.) with the specific lowercase entity name they refer to based on the text context (e.g., 'marie curie').
6.  **Specificity:** Capture specific details (e.g., 'nobel prize in physics' instead of just 'nobel prize' if specified).
7.  **Completeness:** Extract all distinct factual relationships mentioned.

**Text to Process:**
```text
{text_chunk}
```

**Required JSON Output Format Example:**
[
  {{ "subject": "marie curie", "predicate": "discovered", "object": "radium" }},
  {{ "subject": "marie curie", "predicate": "won", "object": "nobel prize in physics" }}
]

**Your JSON Output (MUST start with '[' and end with ']'):**
"""

Let's display the prompts we've defined to verify them.

In [44]:
print("--- System Prompt ---")
print(extraction_system_prompt)
print("\n" + "-" * 25 + "\n")

print("--- User Prompt Template (Structure) ---")
# Show structure, replacing the placeholder for clarity
print(
    extraction_user_prompt_template.replace(
        "{text_chunk}", "[... text chunk goes here ...]"
    )
)
print("\n" + "-" * 25 + "\n")

# Show an example of the *actual* prompt that will be sent for the first chunk
print("--- Example Filled User Prompt (for Chunk 1) ---")
if chunks:
    example_filled_prompt = extraction_user_prompt_template.format(
        text_chunk=chunks[0]["text"]
    )
    # Displaying a limited portion for brevity
    print(
        example_filled_prompt[:600]
        + "\n[... rest of chunk text ...]\n"
        + example_filled_prompt[-200:]
    )
else:
    print("No chunks available to create an example filled prompt.")
print("\n" + "-" * 25)

--- System Prompt ---

你是一位处理知识图谱提取的 AI 专家。我将用英文给出 Prompt，但你需要对处理文本中的语言保持原样，即不必翻译为英文后输出。
You are an AI expert specialized in knowledge graph extraction.
Your task is to identify and extract factual Subject-Predicate-Object (SPO) triples from the given text.
Focus on accuracy and adhere strictly to the JSON output format requested in the user prompt.
Extract core entities and the most direct relationship.


-------------------------

--- User Prompt Template (Structure) ---

Please extract Subject-Predicate-Object (S-P-O) triples from the text below. 对于文本中的名词、关系，如果原文使用中文表述，你生成的内容也应该为中文；即：不必将内容翻译为英文再输出。

如果节点和关系中出现用 $$ 括起来的公式，你需要将公式表达为不含 $$ 的文本形式，不使用 latex 语法，不必严谨表述，只要能大致看出公式形式即可。

**VERY IMPORTANT RULES:**
1.  **Output Format:** Respond ONLY with a single, valid JSON array. Each element MUST be an object with keys "subject", "predicate", "object".
2.  **JSON Only:** Do NOT include any text before or after the JSON array (e.g., no 'Here is the JSON:' or explanations). Do NOT use markdown ```json ... ``` tags.
3.  **Concise Predicates:** Keep the 'predicate' value concise (1-3 words, ideally 1-2). Use verbs or short verb phrases (e.g., 'discovered', 'was born in', 'won').
4.  **Lowercase:** ALL values for 'subject', 'predicate', and 'object' MUST be lowercase.
5.  **Pronoun Resolution:** Replace pronouns (she, he, it, her, etc.) with the specific lowercase entity name they refer to based on the text context (e.g., 'marie curie').
6.  **Specificity:** Capture specific details (e.g., 'nobel prize in physics' instead of just 'nobel prize' if specified).
7.  **Completeness:** Extract all distinct factual relationships mentioned.

**Text to Process:**
```text
[... text chunk goes here ...]
```

**Required JSON Output Format Example:**
[
  {{ "subject": "marie curie", "predicate": "discovered", "object": "radium" }},
  {{ "subject": "marie curie", "predicate": "won", "object": "nobel prize in physics" }}
]

**Your JSON Output (MUST start with '[' and end with ']'):**


-------------------------

--- Example Filled User Prompt (for Chunk 1) ---

Please extract Subject-Predicate-Object (S-P-O) triples from the text below. 对于文本中的名词、关系，如果原文使用中文表述，你生成的内容也应该为中文；即：不必将内容翻译为英文再输出。

如果节点和关系中出现用 $$ 括起来的公式，你需要将公式表达为不含 $$ 的文本形式，不使用 latex 语法，不必严谨表述，只要能大致看出公式形式即可。

**VERY IMPORTANT RULES:**
1.  **Output Format:** Respond ONLY with a single, valid JSON array. Each element MUST be an object with keys "subject", "predicate", "object".
2.  **JSON Only:** Do NOT include any text before or after the JSON array (e.g., no 'Here is the JSON:' or explanations). Do NOT use markdown ```json ... ``` tags.
3.  **Concise Predicates:** Keep the 'predicate' value
[... rest of chunk text ...]
"predicate": "discovered", "object": "radium" },
  { "subject": "marie curie", "predicate": "won", "object": "nobel prize in physics" }
]

**Your JSON Output (MUST start with '[' and end with ']'):**


-------------------------

## Step 7: LLM Interaction - Extracting Triples (Chunk by Chunk)

Now we loop through each text chunk, send it to the LLM with our prompts, and attempt to parse the expected JSON output. We will show the process for each chunk.

In [45]:
# Initialize lists to store results and failures
all_extracted_triples = []
failed_chunks = []

print(
    f"Starting triple extraction from {len(chunks)} chunks using model '{llm_model_name}'..."
)
# We will process chunks one by one in the following cells.

Starting triple extraction from 10 chunks using model 'gemini-1.5-flash'...

### Processing Chunk 1 (Example - loop structure will handle all)

In [46]:
# --- This cell represents the core logic inside the loop for ONE chunk ---
# --- In a real run, this logic would be in a loop like the original notebook ---
# --- We show it step-by-step for the first chunk for clarity ---

# chunk_index = 0 # For demonstration, we process only the first chunk here

print("model: ", llm_model_name)

for chunk_index in range(len(chunks)):
    chunk_info = chunks[chunk_index]
    chunk_text = chunk_info["text"]
    chunk_num = chunk_info["chunk_number"]

    print(f"\n--- Processing Chunk {chunk_num}/{len(chunks)} --- ")

    # 1. Format the User Prompt
    print("1. Formatting User Prompt...")
    user_prompt = extraction_user_prompt_template.format(text_chunk=chunk_text)
    # print(f"   Formatted Prompt (Snippet): {user_prompt[:200]}...{user_prompt[-100:]}") # Optional: View prompt

    llm_output = None
    error_message = None

    try:
        # 2. Make the API Call
        print("2. Sending request to LLM...")
        response = client.chat.completions.create(
            model=llm_model_name,
            messages=[
                {"role": "system", "content": extraction_system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            temperature=llm_temperature,
            max_tokens=llm_max_tokens,
            # Request JSON output format - helps models that support it
            response_format={"type": "json_object"},
        )
        print("   LLM response received.")

        # 3. Extract Raw Response Content
        print("3. Extracting raw response content...")
        llm_output = response.choices[0].message.content.strip()
        print("--- Raw LLM Output (Chunk {chunk_num}) ---")
        print(llm_output)
        print("-" * 20)

    except Exception as e:
        error_message = str(e)
        print(f"   ERROR during API call: {error_message}")
        failed_chunks.append(
            {
                "chunk_number": chunk_num,
                "error": f"API/Processing Error: {error_message}",
                "response": "",
            }
        )

    # 4. Parse JSON (if API call succeeded)
    parsed_json = None
    parsing_error = None
    if llm_output is not None:
        print("4. Attempting to parse JSON from response...")
        try:
            # Strategy 1: Direct parsing (ideal)
            parsed_data = json.loads(llm_output)

            # Handle if response_format={'type':'json_object'} returns a dict containing the list
            if isinstance(parsed_data, dict):
                print("   Detected dictionary response, attempting to extract list...")
                list_values = [v for v in parsed_data.values() if isinstance(v, list)]
                if len(list_values) == 1:
                    parsed_json = list_values[0]
                    print("      Successfully extracted list from dictionary.")
                else:
                    raise ValueError(
                        "JSON object received, but doesn't contain a single list of triples."
                    )
            elif isinstance(parsed_data, list):
                parsed_json = parsed_data
                print("   Successfully parsed JSON list directly.")
            else:
                raise ValueError(
                    "Parsed JSON is not a list or expected dictionary wrapper."
                )

        except json.JSONDecodeError as json_err:
            parsing_error = f"JSONDecodeError: {json_err}. Trying regex fallback..."
            print(f"   {parsing_error}")
            # Strategy 2: Regex fallback for arrays potentially wrapped in text/markdown
            match = re.search(r"^\s*(\[.*?\])\s*$", llm_output, re.DOTALL)
            if match:
                json_string_extracted = match.group(1)
                print("      Regex found potential JSON array structure.")
                try:
                    parsed_json = json.loads(json_string_extracted)
                    print("      Successfully parsed JSON from regex extraction.")
                    parsing_error = None  # Clear previous error
                except json.JSONDecodeError as nested_err:
                    parsing_error = f"JSONDecodeError after regex: {nested_err}"
                    print(f"      ERROR: Regex content is not valid JSON: {nested_err}")
            else:
                parsing_error = "JSONDecodeError and Regex fallback failed."
                print("      ERROR: Regex could not find JSON array structure.")

        except ValueError as val_err:
            parsing_error = (
                f"ValueError: {val_err}"  # Catches issues with unexpected structure
            )
            print(f"   ERROR: {parsing_error}")

        # --- Show Parsed Result (or error) ---
        if parsed_json is not None:
            print("--- Parsed JSON Data (Chunk {chunk_num}) ---")
            print(json.dumps(parsed_json, indent=2))  # Pretty print the JSON
            print("-" * 20)
        else:
            print(f"--- JSON Parsing FAILED (Chunk {chunk_num}) --- ")
            print(f"   Final Parsing Error: {parsing_error}")
            print("-" * 20)
            failed_chunks.append(
                {
                    "chunk_number": chunk_num,
                    "error": f"Parsing Failed: {parsing_error}",
                    "response": llm_output,
                }
            )

    # 5. Validate and Store Triples (if parsing succeeded)
    if parsed_json is not None:
        print("5. Validating structure and extracting triples...")
        valid_triples_in_chunk = []
        invalid_entries = []
        if isinstance(parsed_json, list):
            for item in parsed_json:
                if isinstance(item, dict) and all(
                    k in item for k in ["subject", "predicate", "object"]
                ):
                    # Basic check: ensure values are strings (can be refined)
                    if all(
                        isinstance(item[k], str)
                        for k in ["subject", "predicate", "object"]
                    ):
                        item["chunk"] = chunk_num  # Add source chunk info
                        valid_triples_in_chunk.append(item)
                    else:
                        invalid_entries.append(
                            {"item": item, "reason": "Non-string value"}
                        )
                else:
                    invalid_entries.append(
                        {"item": item, "reason": "Incorrect structure/keys"}
                    )
        else:
            print("   ERROR: Parsed data is not a list, cannot extract triples.")
            invalid_entries.append({"item": parsed_json, "reason": "Not a list"})
            # Also add to failed chunks if the overall structure was wrong
            if not any(fc["chunk_number"] == chunk_num for fc in failed_chunks):
                failed_chunks.append(
                    {
                        "chunk_number": chunk_num,
                        "error": "Parsed data not a list",
                        "response": llm_output,
                    }
                )

        # --- Show Validation Results ---
        print(f"   Found {len(valid_triples_in_chunk)} valid triples in this chunk.")
        if invalid_entries:
            print(f"   Skipped {len(invalid_entries)} invalid entries.")
            # print(f"   Invalid entries details: {invalid_entries}") # Uncomment for debugging

        # --- Display Valid Triples from this Chunk ---
        if valid_triples_in_chunk:
            print(f"--- Valid Triples Extracted (Chunk {chunk_num}) ---")
            display(pd.DataFrame(valid_triples_in_chunk))
            print("-" * 20)
            # Add to the main list
            all_extracted_triples.extend(valid_triples_in_chunk)
        else:
            print("--- No valid triples extracted from this chunk. ---")
            print("-" * 20)

    # --- Update Running Total (Visual Feedback) ---
    print(f"--- Running Total Triples Extracted: {len(all_extracted_triples)} --- ")
    print(f"--- Failed Chunks So Far: {len(failed_chunks)} --- ")

print("\nFinished processing this chunk.")
# --- IMPORTANT: In a full run, you would uncomment the loop in the original notebook ---
# --- and remove the `chunk_index = 0` line to process ALL chunks. ---

model:  gemini-1.5-flash

--- Processing Chunk 1/10 ---
1. Formatting User Prompt...
2. Sending request to LLM...
   LLM response received.
3. Extracting raw response content...
--- Raw LLM Output (Chunk {chunk_num}) ---
[{"subject": "动物", "predicate": "是", "object": "地球上生物多样性的重要组成部分"}, {"subject": "动物", "predicate": "与", "object": "植物、微生物共同构成复杂的生态系统"}, {"subject": "动物", "predicate": "维持着", "object": "地球的生态平衡"}, {"subject": "动物", "predicate": "是", "object": "大自然奇迹"}, {"subject": "地球上的动物", "predicate": "种类", "object": "繁多"}, {"subject": "昆虫", "predicate": "占据了", "object": "地球的每一个角落"}, {"subject": "大象等大型动物", "predicate": "以", "object": "体型和力量令人惊叹"}, {"subject": "每种动物", "predicate": "通过进化发展出", "object": "适应其生存环境的独特特征"}, {"subject": "动物", "predicate": "与", "object": "人类有着密切的关系"}, {"subject": "很多动物", "predicate": "扮演着", "object": "朋友、助手或工作伙伴的角色"}, {"subject": "宠物", "predicate": "给予", "object": "人类无尽的陪伴和情感支持"}, {"subject": "一些工作动物", "predicate": "帮助", "object": "人类完成某些特殊任务"}, {"subject": "动物", "predicate": "在", "object": "农业和科研中扮演着重要角色"}, {"subject": "家畜和家禽", "predicate": "为", "object": "人类提供食物来源"}, {"subject": "实验动物", "predicate": "是", "object": "科学研究的重要对象"}, {"subject": "人类活动", "predicate": "威胁着", "object": "动物的栖息地"}, {"subject": "工业化进程、城市化扩张、森林砍伐", "predicate": "导致", "object": "许多物种濒临灭绝"}, {"subject": "偷猎和非法贸易", "predicate": "加剧了", "object": "某些物种的生存危机"}, {"subject": "各国政府和国际组织", "predicate": "加强", "object": "动物保护法律法规"}]
--------------------
4. Attempting to parse JSON from response...
   Successfully parsed JSON list directly.
--- Parsed JSON Data (Chunk {chunk_num}) ---
[
  {
    "subject": "\u52a8\u7269",
    "predicate": "\u662f",
    "object": "\u5730\u7403\u4e0a\u751f\u7269\u591a\u6837\u6027\u7684\u91cd\u8981\u7ec4\u6210\u90e8\u5206"
  },
  {
    "subject": "\u52a8\u7269",
    "predicate": "\u4e0e",
    "object": "\u690d\u7269\u3001\u5fae\u751f\u7269\u5171\u540c\u6784\u6210\u590d\u6742\u7684\u751f\u6001\u7cfb\u7edf"
  },
  {
    "subject": "\u52a8\u7269",
    "predicate": "\u7ef4\u6301\u7740",
    "object": "\u5730\u7403\u7684\u751f\u6001\u5e73\u8861"
  },
  {
    "subject": "\u52a8\u7269",
    "predicate": "\u662f",
    "object": "\u5927\u81ea\u7136\u5947\u8ff9"
  },
  {
    "subject": "\u5730\u7403\u4e0a\u7684\u52a8\u7269",
    "predicate": "\u79cd\u7c7b",
    "object": "\u7e41\u591a"
  },
  {
    "subject": "\u6606\u866b",
    "predicate": "\u5360\u636e\u4e86",
    "object": "\u5730\u7403\u7684\u6bcf\u4e00\u4e2a\u89d2\u843d"
  },
  {
    "subject": "\u5927\u8c61\u7b49\u5927\u578b\u52a8\u7269",
    "predicate": "\u4ee5",
    "object": "\u4f53\u578b\u548c\u529b\u91cf\u4ee4\u4eba\u60ca\u53f9"
  },
  {
    "subject": "\u6bcf\u79cd\u52a8\u7269",
    "predicate": "\u901a\u8fc7\u8fdb\u5316\u53d1\u5c55\u51fa",
    "object": "\u9002\u5e94\u5176\u751f\u5b58\u73af\u5883\u7684\u72ec\u7279\u7279\u5f81"
  },
  {
    "subject": "\u52a8\u7269",
    "predicate": "\u4e0e",
    "object": "\u4eba\u7c7b\u6709\u7740\u5bc6\u5207\u7684\u5173\u7cfb"
  },
  {
    "subject": "\u5f88\u591a\u52a8\u7269",
    "predicate": "\u626e\u6f14\u7740",
    "object": "\u670b\u53cb\u3001\u52a9\u624b\u6216\u5de5\u4f5c\u4f19\u4f34\u7684\u89d2\u8272"
  },
  {
    "subject": "\u5ba0\u7269",
    "predicate": "\u7ed9\u4e88",
    "object": "\u4eba\u7c7b\u65e0\u5c3d\u7684\u966a\u4f34\u548c\u60c5\u611f\u652f\u6301"
  },
  {
    "subject": "\u4e00\u4e9b\u5de5\u4f5c\u52a8\u7269",
    "predicate": "\u5e2e\u52a9",
    "object": "\u4eba\u7c7b\u5b8c\u6210\u67d0\u4e9b\u7279\u6b8a\u4efb\u52a1"
  },
  {
    "subject": "\u52a8\u7269",
    "predicate": "\u5728",
    "object": "\u519c\u4e1a\u548c\u79d1\u7814\u4e2d\u626e\u6f14\u7740\u91cd\u8981\u89d2\u8272"
  },
  {
    "subject": "\u5bb6\u755c\u548c\u5bb6\u79bd",
    "predicate": "\u4e3a",
    "object": "\u4eba\u7c7b\u63d0\u4f9b\u98df\u7269\u6765\u6e90"
  },
  {
    "subject": "\u5b9e\u9a8c\u52a8\u7269",
    "predicate": "\u662f",
    "object": "\u79d1\u5b66\u7814\u7a76\u7684\u91cd\u8981\u5bf9\u8c61"
  },
  {
    "subject": "\u4eba\u7c7b\u6d3b\u52a8",
    "predicate": "\u5a01\u80c1\u7740",
    "object": "\u52a8\u7269\u7684\u6816\u606f\u5730"
  },
  {
    "subject": "\u5de5\u4e1a\u5316\u8fdb\u7a0b\u3001\u57ce\u5e02\u5316\u6269\u5f20\u3001\u68ee\u6797\u780d\u4f10",
    "predicate": "\u5bfc\u81f4",
    "object": "\u8bb8\u591a\u7269\u79cd\u6fd2\u4e34\u706d\u7edd"
  },
  {
    "subject": "\u5077\u730e\u548c\u975e\u6cd5\u8d38\u6613",
    "predicate": "\u52a0\u5267\u4e86",
    "object": "\u67d0\u4e9b\u7269\u79cd\u7684\u751f\u5b58\u5371\u673a"
  },
  {
    "subject": "\u5404\u56fd\u653f\u5e9c\u548c\u56fd\u9645\u7ec4\u7ec7",
    "predicate": "\u52a0\u5f3a",
    "object": "\u52a8\u7269\u4fdd\u62a4\u6cd5\u5f8b\u6cd5\u89c4"
  }
]
--------------------
5. Validating structure and extracting triples...
   Found 19 valid triples in this chunk.
--- Valid Triples Extracted (Chunk 1) ---

             subject predicate             object  chunk
0                 动物         是    地球上生物多样性的重要组成部分      1
1                 动物         与  植物、微生物共同构成复杂的生态系统      1
2                 动物       维持着            地球的生态平衡      1
3                 动物         是              大自然奇迹      1
4             地球上的动物        种类                 繁多      1
5                 昆虫       占据了           地球的每一个角落      1
6            大象等大型动物         以          体型和力量令人惊叹      1
7               每种动物   通过进化发展出       适应其生存环境的独特特征      1
8                 动物         与          人类有着密切的关系      1
9               很多动物       扮演着      朋友、助手或工作伙伴的角色      1
10                宠物        给予       人类无尽的陪伴和情感支持      1
11            一些工作动物        帮助         人类完成某些特殊任务      1
12                动物         在      农业和科研中扮演着重要角色      1
13             家畜和家禽         为           人类提供食物来源      1
14              实验动物         是          科学研究的重要对象      1
15              人类活动       威胁着             动物的栖息地      1
16  工业化进程、城市化扩张、森林砍伐        导致           许多物种濒临灭绝      1
17           偷猎和非法贸易       加剧了          某些物种的生存危机      1
18         各国政府和国际组织        加强           动物保护法律法规      1

--------------------
--- Running Total Triples Extracted: 19 ---
--- Failed Chunks So Far: 0 ---

--- Processing Chunk 2/10 ---
1. Formatting User Prompt...
2. Sending request to LLM...
   LLM response received.
3. Extracting raw response content...
--- Raw LLM Output (Chunk {chunk_num}) ---
[{"subject": "偷猎和非法贸易", "predicate": "加剧", "object": "某些物种的生存危机"}, {"subject": "各国政府和国际组织", "predicate": "加强", "object": "动物保护法律法规"}, {"subject": "各国政府和国际组织", "predicate": "推动", "object": "拯救濒危动物的努力"}, {"subject": "许多文化", "predicate": "视为", "object": "神灵的化身或图腾"}, {"subject": "动物", "predicate": "承载", "object": "丰厚的历史和信仰"}, {"subject": "动物角色", "predicate": "用来表现", "object": "人类无法用语言表达的情感和哲理"}, {"subject": "动物", "predicate": "是", "object": "自然界的珍宝"}, {"subject": "动物", "predicate": "是", "object": "人类的朋友和老师"}, {"subject": "保护动物及其生存环境", "predicate": "是", "object": "保护我们生态系统"}, {"subject": "保护动物及其生存环境", "predicate": "是", "object": "保护人类自身的未来"}, {"subject": "猫", "predicate": "是", "object": "一种常见的宠物"}, {"subject": "猫", "predicate": "闻名于", "object": "温顺和独立性"}, {"subject": "猫", "predicate": "有", "object": "柔软的毛发"}, {"subject": "猫", "predicate": "有", "object": "敏锐的感官"}, {"subject": "猫", "predicate": "有", "object": "敏捷的动作"}, {"subject": "猫", "predicate": "可以", "object": "很好地适应各种居住环境"}, {"subject": "猫的呼噜声", "predicate": "被认为具有", "object": "舒缓和疗愈作用"}, {"subject": "狗", "predicate": "是", "object": "人类的宠物"}, {"subject": "狗", "predicate": "是", "object": "人类最好的朋友之一"}, {"subject": "狗", "predicate": "能够提供", "object": "陪伴"}, {"subject": "狗", "predicate": "能够", "object": "保护家庭"}, {"subject": "狗", "predicate": "可以进行", "object": "各种工作"}, {"subject": "狗", "predicate": "有", "object": "很多品种"}]
--------------------
4. Attempting to parse JSON from response...
   Successfully parsed JSON list directly.
--- Parsed JSON Data (Chunk {chunk_num}) ---
[
  {
    "subject": "\u5077\u730e\u548c\u975e\u6cd5\u8d38\u6613",
    "predicate": "\u52a0\u5267",
    "object": "\u67d0\u4e9b\u7269\u79cd\u7684\u751f\u5b58\u5371\u673a"
  },
  {
    "subject": "\u5404\u56fd\u653f\u5e9c\u548c\u56fd\u9645\u7ec4\u7ec7",
    "predicate": "\u52a0\u5f3a",
    "object": "\u52a8\u7269\u4fdd\u62a4\u6cd5\u5f8b\u6cd5\u89c4"
  },
  {
    "subject": "\u5404\u56fd\u653f\u5e9c\u548c\u56fd\u9645\u7ec4\u7ec7",
    "predicate": "\u63a8\u52a8",
    "object": "\u62ef\u6551\u6fd2\u5371\u52a8\u7269\u7684\u52aa\u529b"
  },
  {
    "subject": "\u8bb8\u591a\u6587\u5316",
    "predicate": "\u89c6\u4e3a",
    "object": "\u795e\u7075\u7684\u5316\u8eab\u6216\u56fe\u817e"
  },
  {
    "subject": "\u52a8\u7269",
    "predicate": "\u627f\u8f7d",
    "object": "\u4e30\u539a\u7684\u5386\u53f2\u548c\u4fe1\u4ef0"
  },
  {
    "subject": "\u52a8\u7269\u89d2\u8272",
    "predicate": "\u7528\u6765\u8868\u73b0",
    "object": "\u4eba\u7c7b\u65e0\u6cd5\u7528\u8bed\u8a00\u8868\u8fbe\u7684\u60c5\u611f\u548c\u54f2\u7406"
  },
  {
    "subject": "\u52a8\u7269",
    "predicate": "\u662f",
    "object": "\u81ea\u7136\u754c\u7684\u73cd\u5b9d"
  },
  {
    "subject": "\u52a8\u7269",
    "predicate": "\u662f",
    "object": "\u4eba\u7c7b\u7684\u670b\u53cb\u548c\u8001\u5e08"
  },
  {
    "subject": "\u4fdd\u62a4\u52a8\u7269\u53ca\u5176\u751f\u5b58\u73af\u5883",
    "predicate": "\u662f",
    "object": "\u4fdd\u62a4\u6211\u4eec\u751f\u6001\u7cfb\u7edf"
  },
  {
    "subject": "\u4fdd\u62a4\u52a8\u7269\u53ca\u5176\u751f\u5b58\u73af\u5883",
    "predicate": "\u662f",
    "object": "\u4fdd\u62a4\u4eba\u7c7b\u81ea\u8eab\u7684\u672a\u6765"
  },
  {
    "subject": "\u732b",
    "predicate": "\u662f",
    "object": "\u4e00\u79cd\u5e38\u89c1\u7684\u5ba0\u7269"
  },
  {
    "subject": "\u732b",
    "predicate": "\u95fb\u540d\u4e8e",
    "object": "\u6e29\u987a\u548c\u72ec\u7acb\u6027"
  },
  {
    "subject": "\u732b",
    "predicate": "\u6709",
    "object": "\u67d4\u8f6f\u7684\u6bdb\u53d1"
  },
  {
    "subject": "\u732b",
    "predicate": "\u6709",
    "object": "\u654f\u9510\u7684\u611f\u5b98"
  },
  {
    "subject": "\u732b",
    "predicate": "\u6709",
    "object": "\u654f\u6377\u7684\u52a8\u4f5c"
  },
  {
    "subject": "\u732b",
    "predicate": "\u53ef\u4ee5",
    "object": "\u5f88\u597d\u5730\u9002\u5e94\u5404\u79cd\u5c45\u4f4f\u73af\u5883"
  },
  {
    "subject": "\u732b\u7684\u547c\u565c\u58f0",
    "predicate": "\u88ab\u8ba4\u4e3a\u5177\u6709",
    "object": "\u8212\u7f13\u548c\u7597\u6108\u4f5c\u7528"
  },
  {
    "subject": "\u72d7",
    "predicate": "\u662f",
    "object": "\u4eba\u7c7b\u7684\u5ba0\u7269"
  },
  {
    "subject": "\u72d7",
    "predicate": "\u662f",
    "object": "\u4eba\u7c7b\u6700\u597d\u7684\u670b\u53cb\u4e4b\u4e00"
  },
  {
    "subject": "\u72d7",
    "predicate": "\u80fd\u591f\u63d0\u4f9b",
    "object": "\u966a\u4f34"
  },
  {
    "subject": "\u72d7",
    "predicate": "\u80fd\u591f",
    "object": "\u4fdd\u62a4\u5bb6\u5ead"
  },
  {
    "subject": "\u72d7",
    "predicate": "\u53ef\u4ee5\u8fdb\u884c",
    "object": "\u5404\u79cd\u5de5\u4f5c"
  },
  {
    "subject": "\u72d7",
    "predicate": "\u6709",
    "object": "\u5f88\u591a\u54c1\u79cd"
  }
]
--------------------
5. Validating structure and extracting triples...
   Found 23 valid triples in this chunk.
--- Valid Triples Extracted (Chunk 2) ---

       subject predicate           object  chunk
0      偷猎和非法贸易        加剧        某些物种的生存危机      2
1    各国政府和国际组织        加强         动物保护法律法规      2
2    各国政府和国际组织        推动        拯救濒危动物的努力      2
3         许多文化        视为         神灵的化身或图腾      2
4           动物        承载         丰厚的历史和信仰      2
5         动物角色      用来表现  人类无法用语言表达的情感和哲理      2
6           动物         是           自然界的珍宝      2
7           动物         是         人类的朋友和老师      2
8   保护动物及其生存环境         是         保护我们生态系统      2
9   保护动物及其生存环境         是        保护人类自身的未来      2
10           猫         是          一种常见的宠物      2
11           猫       闻名于           温顺和独立性      2
12           猫         有            柔软的毛发      2
13           猫         有            敏锐的感官      2
14           猫         有            敏捷的动作      2
15           猫        可以      很好地适应各种居住环境      2
16       猫的呼噜声     被认为具有          舒缓和疗愈作用      2
17           狗         是            人类的宠物      2
18           狗         是        人类最好的朋友之一      2
19           狗      能够提供               陪伴      2
20           狗        能够             保护家庭      2
21           狗      可以进行             各种工作      2
22           狗         有             很多品种      2

--------------------
--- Running Total Triples Extracted: 42 ---
--- Failed Chunks So Far: 0 ---

--- Processing Chunk 3/10 ---
1. Formatting User Prompt...
2. Sending request to LLM...
   LLM response received.
3. Extracting raw response content...
--- Raw LLM Output (Chunk {chunk_num}) ---
[{"subject": "狗", "predicate": "扮演", "object": "重要角色"}, {"subject": "狐狸", "predicate": "属于", "object": "犬科动物"}, {"subject": "狐狸", "predicate": "闻名", "object": "聪明,狡猾"}, {"subject": "狐狸", "predicate": "具有", "object": "尖尖的鼻子和耳朵"}, {"subject": "狐狸", "predicate": "以", "object": "小型哺乳动物、鸟类以及昆虫为食"}, {"subject": "狐狸", "predicate": "吃", "object": "植物果实"}, {"subject": "狐狸", "predicate": "是", "object": "独居动物"}, {"subject": "狐狸", "predicate": "交往", "object": "其他狐狸"}, {"subject": "狐狸", "predicate": "建立", "object": "自己的领地"}, {"subject": "母狐狸", "predicate": "产仔", "object": "隐蔽的巢穴"}, {"subject": "狐狸", "predicate": "被看作", "object": "善于变化和狡黠的化身"}]
--------------------
4. Attempting to parse JSON from response...
   Successfully parsed JSON list directly.
--- Parsed JSON Data (Chunk {chunk_num}) ---
[
  {
    "subject": "\u72d7",
    "predicate": "\u626e\u6f14",
    "object": "\u91cd\u8981\u89d2\u8272"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u5c5e\u4e8e",
    "object": "\u72ac\u79d1\u52a8\u7269"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u95fb\u540d",
    "object": "\u806a\u660e,\u72e1\u733e"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u5177\u6709",
    "object": "\u5c16\u5c16\u7684\u9f3b\u5b50\u548c\u8033\u6735"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u4ee5",
    "object": "\u5c0f\u578b\u54fa\u4e73\u52a8\u7269\u3001\u9e1f\u7c7b\u4ee5\u53ca\u6606\u866b\u4e3a\u98df"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u5403",
    "object": "\u690d\u7269\u679c\u5b9e"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u662f",
    "object": "\u72ec\u5c45\u52a8\u7269"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u4ea4\u5f80",
    "object": "\u5176\u4ed6\u72d0\u72f8"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u5efa\u7acb",
    "object": "\u81ea\u5df1\u7684\u9886\u5730"
  },
  {
    "subject": "\u6bcd\u72d0\u72f8",
    "predicate": "\u4ea7\u4ed4",
    "object": "\u9690\u853d\u7684\u5de2\u7a74"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u88ab\u770b\u4f5c",
    "object": "\u5584\u4e8e\u53d8\u5316\u548c\u72e1\u9ee0\u7684\u5316\u8eab"
  }
]
--------------------
5. Validating structure and extracting triples...
   Found 11 valid triples in this chunk.
--- Valid Triples Extracted (Chunk 3) ---

   subject predicate           object  chunk
0        狗        扮演             重要角色      3
1       狐狸        属于             犬科动物      3
2       狐狸        闻名            聪明,狡猾      3
3       狐狸        具有         尖尖的鼻子和耳朵      3
4       狐狸         以  小型哺乳动物、鸟类以及昆虫为食      3
5       狐狸         吃             植物果实      3
6       狐狸         是             独居动物      3
7       狐狸        交往             其他狐狸      3
8       狐狸        建立            自己的领地      3
9      母狐狸        产仔            隐蔽的巢穴      3
10      狐狸       被看作       善于变化和狡黠的化身      3

--------------------
--- Running Total Triples Extracted: 53 ---
--- Failed Chunks So Far: 0 ---

--- Processing Chunk 4/10 ---
1. Formatting User Prompt...
2. Sending request to LLM...
   LLM response received.
3. Extracting raw response content...
--- Raw LLM Output (Chunk {chunk_num}) ---
[{"subject": "狐狸", "predicate": "被赋予", "object": "不同角色"}, {"subject": "狐狸", "predicate": "被看作", "object": "善于变化和狡黠的化身"}, {"subject": "狐狸", "predicate": "被刻画成", "object": "聪明形象"}, {"subject": "狐狸", "predicate": "运用", "object": "智谋"}, {"subject": "狐狸", "predicate": "通过", "object": "诡计"}, {"subject": "狐狸", "predicate": "被视为", "object": "害兽"}, {"subject": "狐狸", "predicate": "扮演", "object": "重要角色"}, {"subject": "狐狸", "predicate": "帮助控制", "object": "啮齿动物数量"}, {"subject": "狐狸", "predicate": "成为", "object": "食物链一部分"}, {"subject": "人们对狐狸的态度", "predicate": "改变", "object": "随着时间推移"}, {"subject": "狐狸皮", "predicate": "被广泛使用于", "object": "毛皮工业"}, {"subject": "野生狐狸生存状态", "predicate": "得到", "object": "更大关注"}, {"subject": "狐狸", "predicate": "是", "object": "生态系统重要组成部分"}, {"subject": "狐狸", "predicate": "成为", "object": "保护生态平衡重要对象"}, {"subject": "狐狸", "predicate": "是", "object": "极具适应能力的动物"}, {"subject": "狐狸", "predicate": "成为", "object": "自然界特殊存在"}, {"subject": "狐狸", "predicate": "成为", "object": "具有性格化特征的动物"}, {"subject": "狐狸形象", "predicate": "愈发", "object": "丰富和立体"}, {"subject": "狐狸", "predicate": "是", "object": "自然界的精灵"}, {"subject": "狐狸", "predicate": "成为", "object": "激发人们创造灵感源泉"}, {"subject": "狐狸的故事和传说", "predicate": "继续", "object": "流传"}]
--------------------
4. Attempting to parse JSON from response...
   Successfully parsed JSON list directly.
--- Parsed JSON Data (Chunk {chunk_num}) ---
[
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u88ab\u8d4b\u4e88",
    "object": "\u4e0d\u540c\u89d2\u8272"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u88ab\u770b\u4f5c",
    "object": "\u5584\u4e8e\u53d8\u5316\u548c\u72e1\u9ee0\u7684\u5316\u8eab"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u88ab\u523b\u753b\u6210",
    "object": "\u806a\u660e\u5f62\u8c61"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u8fd0\u7528",
    "object": "\u667a\u8c0b"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u901a\u8fc7",
    "object": "\u8be1\u8ba1"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u88ab\u89c6\u4e3a",
    "object": "\u5bb3\u517d"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u626e\u6f14",
    "object": "\u91cd\u8981\u89d2\u8272"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u5e2e\u52a9\u63a7\u5236",
    "object": "\u556e\u9f7f\u52a8\u7269\u6570\u91cf"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u6210\u4e3a",
    "object": "\u98df\u7269\u94fe\u4e00\u90e8\u5206"
  },
  {
    "subject": "\u4eba\u4eec\u5bf9\u72d0\u72f8\u7684\u6001\u5ea6",
    "predicate": "\u6539\u53d8",
    "object": "\u968f\u7740\u65f6\u95f4\u63a8\u79fb"
  },
  {
    "subject": "\u72d0\u72f8\u76ae",
    "predicate": "\u88ab\u5e7f\u6cdb\u4f7f\u7528\u4e8e",
    "object": "\u6bdb\u76ae\u5de5\u4e1a"
  },
  {
    "subject": "\u91ce\u751f\u72d0\u72f8\u751f\u5b58\u72b6\u6001",
    "predicate": "\u5f97\u5230",
    "object": "\u66f4\u5927\u5173\u6ce8"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u662f",
    "object": "\u751f\u6001\u7cfb\u7edf\u91cd\u8981\u7ec4\u6210\u90e8\u5206"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u6210\u4e3a",
    "object": "\u4fdd\u62a4\u751f\u6001\u5e73\u8861\u91cd\u8981\u5bf9\u8c61"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u662f",
    "object": "\u6781\u5177\u9002\u5e94\u80fd\u529b\u7684\u52a8\u7269"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u6210\u4e3a",
    "object": "\u81ea\u7136\u754c\u7279\u6b8a\u5b58\u5728"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u6210\u4e3a",
    "object": "\u5177\u6709\u6027\u683c\u5316\u7279\u5f81\u7684\u52a8\u7269"
  },
  {
    "subject": "\u72d0\u72f8\u5f62\u8c61",
    "predicate": "\u6108\u53d1",
    "object": "\u4e30\u5bcc\u548c\u7acb\u4f53"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u662f",
    "object": "\u81ea\u7136\u754c\u7684\u7cbe\u7075"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u6210\u4e3a",
    "object": "\u6fc0\u53d1\u4eba\u4eec\u521b\u9020\u7075\u611f\u6e90\u6cc9"
  },
  {
    "subject": "\u72d0\u72f8\u7684\u6545\u4e8b\u548c\u4f20\u8bf4",
    "predicate": "\u7ee7\u7eed",
    "object": "\u6d41\u4f20"
  }
]
--------------------
5. Validating structure and extracting triples...
   Found 21 valid triples in this chunk.
--- Valid Triples Extracted (Chunk 4) ---

     subject predicate      object  chunk
0         狐狸       被赋予        不同角色      4
1         狐狸       被看作  善于变化和狡黠的化身      4
2         狐狸      被刻画成        聪明形象      4
3         狐狸        运用          智谋      4
4         狐狸        通过          诡计      4
5         狐狸       被视为          害兽      4
6         狐狸        扮演        重要角色      4
7         狐狸      帮助控制      啮齿动物数量      4
8         狐狸        成为      食物链一部分      4
9   人们对狐狸的态度        改变      随着时间推移      4
10       狐狸皮    被广泛使用于        毛皮工业      4
11  野生狐狸生存状态        得到        更大关注      4
12        狐狸         是  生态系统重要组成部分      4
13        狐狸        成为  保护生态平衡重要对象      4
14        狐狸         是   极具适应能力的动物      4
15        狐狸        成为     自然界特殊存在      4
16        狐狸        成为  具有性格化特征的动物      4
17      狐狸形象        愈发       丰富和立体      4
18        狐狸         是      自然界的精灵      4
19        狐狸        成为  激发人们创造灵感源泉      4
20  狐狸的故事和传说        继续          流传      4

--------------------
--- Running Total Triples Extracted: 74 ---
--- Failed Chunks So Far: 0 ---

--- Processing Chunk 5/10 ---
1. Formatting User Prompt...
2. Sending request to LLM...
   LLM response received.
3. Extracting raw response content...
--- Raw LLM Output (Chunk {chunk_num}) ---
[{"subject": "狐狸", "predicate": "是", "object": "自然界精灵"}, {"subject": "狐狸", "predicate": "成为", "object": "激发人们创造灵感源泉"}, {"subject": "狐狸的故事和传说", "predicate": "将继续", "object": "流传"}, {"subject": "狐狸的故事和传说", "predicate": "成为", "object": "人类文化一部分"}, {"subject": "狐狸的名声和象征意义", "predicate": "得到", "object": "广泛认可"}, {"subject": "仓鼠", "predicate": "是", "object": "一种小型啮齿动物"}, {"subject": "仓鼠", "predicate": "属于", "object": "仓鼠科"}, {"subject": "仓鼠", "predicate": "体型", "object": "娇小"}, {"subject": "仓鼠", "predicate": "深受", "object": "人们喜爱"}, {"subject": "许多人", "predicate": "选择", "object": "把仓鼠作为宠物饲养"}, {"subject": "仓鼠", "predicate": "主要分布在", "object": "亚洲、欧洲及北美洲地区"}, {"subject": "仓鼠", "predicate": "较为常见于", "object": "中国、俄罗斯和哈萨克斯坦等地"}, {"subject": "仓鼠种类", "predicate": "繁多"}, {"subject": "最常见仓鼠", "predicate": "包括", "object": "金丝熊、坎贝尔仓鼠、加卡利亚仓鼠和罗伯罗夫斯基仓鼠"}, {"subject": "每种仓鼠", "predicate": "有", "object": "自己独特特征"}, {"subject": "金丝熊仓鼠", "predicate": "体型", "object": "较大"}, {"subject": "金丝熊仓鼠", "predicate": "性格", "object": "温顺"}, {"subject": "加卡利亚仓鼠", "predicate": "体型", "object": "较小"}, {"subject": "加卡利亚仓鼠", "predicate": "活泼", "object": "好动"}, {"subject": "仓鼠", "predicate": "生活在", "object": "各种环境"}, {"subject": "仓鼠", "predicate": "可以", "object": "在野外生存"}, {"subject": "仓鼠", "predicate": "能够适应", "object": "人工饲养环境"}, {"subject": "野生仓鼠", "predicate": "通常栖息在", "object": "沙漠、草原"}, {"subject": "沙漠、草原", "predicate": "提供", "object": "充足食物和庇护所"}, {"subject": "仓鼠", "predicate": "是", "object": "夜行动物"}, {"subject": "仓鼠", "predicate": "白天", "object": "躲在洞穴"}, {"subject": "仓鼠", "predicate": "晚上", "object": "出来觅食、活动"}, {"subject": "仓鼠饮食", "predicate": "以", "object": "植物为主"}, {"subject": "仓鼠饮食", "predicate": "主要包括", "object": "各种种子、果实、坚果、谷物"}, {"subject": "仓鼠", "predicate": "偶尔吃", "object": "一些昆虫和小型动物"}, {"subject": "这种饮食习惯", "predicate": "使仓鼠能够", "object": "有效储存食物"}, {"subject": "这种饮食习惯", "predicate": "应对", "object": "食物匮乏"}]
--------------------
4. Attempting to parse JSON from response...
   Successfully parsed JSON list directly.
--- Parsed JSON Data (Chunk {chunk_num}) ---
[
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u662f",
    "object": "\u81ea\u7136\u754c\u7cbe\u7075"
  },
  {
    "subject": "\u72d0\u72f8",
    "predicate": "\u6210\u4e3a",
    "object": "\u6fc0\u53d1\u4eba\u4eec\u521b\u9020\u7075\u611f\u6e90\u6cc9"
  },
  {
    "subject": "\u72d0\u72f8\u7684\u6545\u4e8b\u548c\u4f20\u8bf4",
    "predicate": "\u5c06\u7ee7\u7eed",
    "object": "\u6d41\u4f20"
  },
  {
    "subject": "\u72d0\u72f8\u7684\u6545\u4e8b\u548c\u4f20\u8bf4",
    "predicate": "\u6210\u4e3a",
    "object": "\u4eba\u7c7b\u6587\u5316\u4e00\u90e8\u5206"
  },
  {
    "subject": "\u72d0\u72f8\u7684\u540d\u58f0\u548c\u8c61\u5f81\u610f\u4e49",
    "predicate": "\u5f97\u5230",
    "object": "\u5e7f\u6cdb\u8ba4\u53ef"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u662f",
    "object": "\u4e00\u79cd\u5c0f\u578b\u556e\u9f7f\u52a8\u7269"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u5c5e\u4e8e",
    "object": "\u4ed3\u9f20\u79d1"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u4f53\u578b",
    "object": "\u5a07\u5c0f"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u6df1\u53d7",
    "object": "\u4eba\u4eec\u559c\u7231"
  },
  {
    "subject": "\u8bb8\u591a\u4eba",
    "predicate": "\u9009\u62e9",
    "object": "\u628a\u4ed3\u9f20\u4f5c\u4e3a\u5ba0\u7269\u9972\u517b"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u4e3b\u8981\u5206\u5e03\u5728",
    "object": "\u4e9a\u6d32\u3001\u6b27\u6d32\u53ca\u5317\u7f8e\u6d32\u5730\u533a"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u8f83\u4e3a\u5e38\u89c1\u4e8e",
    "object": "\u4e2d\u56fd\u3001\u4fc4\u7f57\u65af\u548c\u54c8\u8428\u514b\u65af\u5766\u7b49\u5730"
  },
  {
    "subject": "\u4ed3\u9f20\u79cd\u7c7b",
    "predicate": "\u7e41\u591a"
  },
  {
    "subject": "\u6700\u5e38\u89c1\u4ed3\u9f20",
    "predicate": "\u5305\u62ec",
    "object": "\u91d1\u4e1d\u718a\u3001\u574e\u8d1d\u5c14\u4ed3\u9f20\u3001\u52a0\u5361\u5229\u4e9a\u4ed3\u9f20\u548c\u7f57\u4f2f\u7f57\u592b\u65af\u57fa\u4ed3\u9f20"
  },
  {
    "subject": "\u6bcf\u79cd\u4ed3\u9f20",
    "predicate": "\u6709",
    "object": "\u81ea\u5df1\u72ec\u7279\u7279\u5f81"
  },
  {
    "subject": "\u91d1\u4e1d\u718a\u4ed3\u9f20",
    "predicate": "\u4f53\u578b",
    "object": "\u8f83\u5927"
  },
  {
    "subject": "\u91d1\u4e1d\u718a\u4ed3\u9f20",
    "predicate": "\u6027\u683c",
    "object": "\u6e29\u987a"
  },
  {
    "subject": "\u52a0\u5361\u5229\u4e9a\u4ed3\u9f20",
    "predicate": "\u4f53\u578b",
    "object": "\u8f83\u5c0f"
  },
  {
    "subject": "\u52a0\u5361\u5229\u4e9a\u4ed3\u9f20",
    "predicate": "\u6d3b\u6cfc",
    "object": "\u597d\u52a8"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u751f\u6d3b\u5728",
    "object": "\u5404\u79cd\u73af\u5883"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u53ef\u4ee5",
    "object": "\u5728\u91ce\u5916\u751f\u5b58"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u80fd\u591f\u9002\u5e94",
    "object": "\u4eba\u5de5\u9972\u517b\u73af\u5883"
  },
  {
    "subject": "\u91ce\u751f\u4ed3\u9f20",
    "predicate": "\u901a\u5e38\u6816\u606f\u5728",
    "object": "\u6c99\u6f20\u3001\u8349\u539f"
  },
  {
    "subject": "\u6c99\u6f20\u3001\u8349\u539f",
    "predicate": "\u63d0\u4f9b",
    "object": "\u5145\u8db3\u98df\u7269\u548c\u5e87\u62a4\u6240"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u662f",
    "object": "\u591c\u884c\u52a8\u7269"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u767d\u5929",
    "object": "\u8eb2\u5728\u6d1e\u7a74"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u665a\u4e0a",
    "object": "\u51fa\u6765\u89c5\u98df\u3001\u6d3b\u52a8"
  },
  {
    "subject": "\u4ed3\u9f20\u996e\u98df",
    "predicate": "\u4ee5",
    "object": "\u690d\u7269\u4e3a\u4e3b"
  },
  {
    "subject": "\u4ed3\u9f20\u996e\u98df",
    "predicate": "\u4e3b\u8981\u5305\u62ec",
    "object": "\u5404\u79cd\u79cd\u5b50\u3001\u679c\u5b9e\u3001\u575a\u679c\u3001\u8c37\u7269"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u5076\u5c14\u5403",
    "object": "\u4e00\u4e9b\u6606\u866b\u548c\u5c0f\u578b\u52a8\u7269"
  },
  {
    "subject": "\u8fd9\u79cd\u996e\u98df\u4e60\u60ef",
    "predicate": "\u4f7f\u4ed3\u9f20\u80fd\u591f",
    "object": "\u6709\u6548\u50a8\u5b58\u98df\u7269"
  },
  {
    "subject": "\u8fd9\u79cd\u996e\u98df\u4e60\u60ef",
    "predicate": "\u5e94\u5bf9",
    "object": "\u98df\u7269\u532e\u4e4f"
  }
]
--------------------
5. Validating structure and extracting triples...
   Found 31 valid triples in this chunk.
   Skipped 1 invalid entries.
--- Valid Triples Extracted (Chunk 5) ---

       subject predicate                     object  chunk
0           狐狸         是                      自然界精灵      5
1           狐狸        成为                 激发人们创造灵感源泉      5
2     狐狸的故事和传说       将继续                         流传      5
3     狐狸的故事和传说        成为                    人类文化一部分      5
4   狐狸的名声和象征意义        得到                       广泛认可      5
5           仓鼠         是                   一种小型啮齿动物      5
6           仓鼠        属于                        仓鼠科      5
7           仓鼠        体型                         娇小      5
8           仓鼠        深受                       人们喜爱      5
9          许多人        选择                  把仓鼠作为宠物饲养      5
10          仓鼠     主要分布在                亚洲、欧洲及北美洲地区      5
11          仓鼠     较为常见于             中国、俄罗斯和哈萨克斯坦等地      5
12       最常见仓鼠        包括  金丝熊、坎贝尔仓鼠、加卡利亚仓鼠和罗伯罗夫斯基仓鼠      5
13        每种仓鼠         有                     自己独特特征      5
14       金丝熊仓鼠        体型                         较大      5
15       金丝熊仓鼠        性格                         温顺      5
16      加卡利亚仓鼠        体型                         较小      5
17      加卡利亚仓鼠        活泼                         好动      5
18          仓鼠       生活在                       各种环境      5
19          仓鼠        可以                      在野外生存      5
20          仓鼠      能够适应                     人工饲养环境      5
21        野生仓鼠     通常栖息在                      沙漠、草原      5
22       沙漠、草原        提供                   充足食物和庇护所      5
23          仓鼠         是                       夜行动物      5
24          仓鼠        白天                       躲在洞穴      5
25          仓鼠        晚上                    出来觅食、活动      5
26        仓鼠饮食         以                       植物为主      5
27        仓鼠饮食      主要包括              各种种子、果实、坚果、谷物      5
28          仓鼠       偶尔吃                  一些昆虫和小型动物      5
29      这种饮食习惯     使仓鼠能够                     有效储存食物      5
30      这种饮食习惯        应对                       食物匮乏      5

--------------------
--- Running Total Triples Extracted: 105 ---
--- Failed Chunks So Far: 0 ---

--- Processing Chunk 6/10 ---
1. Formatting User Prompt...
2. Sending request to LLM...
   LLM response received.
3. Extracting raw response content...
--- Raw LLM Output (Chunk {chunk_num}) ---
[{"subject": "仓鼠", "predicate": "吃", "object": "坚果"}, {"subject": "仓鼠", "predicate": "吃", "object": "谷物"}, {"subject": "仓鼠", "predicate": "吃", "object": "昆虫"}, {"subject": "仓鼠", "predicate": "吃", "object": "小型动物"}, {"subject": "仓鼠", "predicate": "储存", "object": "食物"}, {"subject": "仓鼠", "predicate": "储存", "object": "食物"}, {"subject": "仓鼠", "predicate": "具备", "object": "将食物储存"}, {"subject": "仓鼠", "predicate": "具备", "object": "将食物储存"}, {"subject": "仓鼠", "predicate": "塞满", "object": "颊囊"}, {"subject": "仓鼠", "predicate": "带回", "object": "巢穴"}, {"subject": "仓鼠", "predicate": "需要", "object": "足够空间"}, {"subject": "笼子", "predicate": "应", "object": "足够宽敞"}, {"subject": "笼子", "predicate": "配备", "object": "跑轮"}, {"subject": "笼子", "predicate": "配备", "object": "隧道"}, {"subject": "笼子", "predicate": "配备", "object": "木屋"}, {"subject": "笼子", "predicate": "配备", "object": "玩具"}, {"subject": "饮水", "predicate": "需要", "object": "每天提供"}, {"subject": "食物", "predicate": "需要", "object": "每天提供"}, {"subject": "饮水", "predicate": "需要", "object": "每天更换"}, {"subject": "食物", "predicate": "需要", "object": "每天更换"}, {"subject": "仓鼠", "predicate": "是", "object": "一种相对独立的动物"}, {"subject": "仓鼠", "predicate": "喜欢", "object": "独居"}, {"subject": "仓鼠", "predicate": "容易", "object": "受到惊吓"}, {"subject": "饲养仓鼠", "predicate": "需要", "object": "注意卫生"}, {"subject": "饲养仓鼠", "predicate": "需要", "object": "定期清理"}, {"subject": "饲养仓鼠", "predicate": "需要", "object": "观察身体状况"}, {"subject": "养仓鼠", "predicate": "带来", "object": "愉悦感"}, {"subject": "养仓鼠", "predicate": "能", "object": "学到知识"}, {"subject": "养仓鼠", "predicate": "教育", "object": "人们"}, {"subject": "仓鼠", "predicate": "是", "object": "一种可爱的动物"}, {"subject": "仓鼠", "predicate": "适合", "object": "家庭饲养"}]
--------------------
4. Attempting to parse JSON from response...
   Successfully parsed JSON list directly.
--- Parsed JSON Data (Chunk {chunk_num}) ---
[
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u5403",
    "object": "\u575a\u679c"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u5403",
    "object": "\u8c37\u7269"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u5403",
    "object": "\u6606\u866b"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u5403",
    "object": "\u5c0f\u578b\u52a8\u7269"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u50a8\u5b58",
    "object": "\u98df\u7269"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u50a8\u5b58",
    "object": "\u98df\u7269"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u5177\u5907",
    "object": "\u5c06\u98df\u7269\u50a8\u5b58"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u5177\u5907",
    "object": "\u5c06\u98df\u7269\u50a8\u5b58"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u585e\u6ee1",
    "object": "\u988a\u56ca"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u5e26\u56de",
    "object": "\u5de2\u7a74"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u9700\u8981",
    "object": "\u8db3\u591f\u7a7a\u95f4"
  },
  {
    "subject": "\u7b3c\u5b50",
    "predicate": "\u5e94",
    "object": "\u8db3\u591f\u5bbd\u655e"
  },
  {
    "subject": "\u7b3c\u5b50",
    "predicate": "\u914d\u5907",
    "object": "\u8dd1\u8f6e"
  },
  {
    "subject": "\u7b3c\u5b50",
    "predicate": "\u914d\u5907",
    "object": "\u96a7\u9053"
  },
  {
    "subject": "\u7b3c\u5b50",
    "predicate": "\u914d\u5907",
    "object": "\u6728\u5c4b"
  },
  {
    "subject": "\u7b3c\u5b50",
    "predicate": "\u914d\u5907",
    "object": "\u73a9\u5177"
  },
  {
    "subject": "\u996e\u6c34",
    "predicate": "\u9700\u8981",
    "object": "\u6bcf\u5929\u63d0\u4f9b"
  },
  {
    "subject": "\u98df\u7269",
    "predicate": "\u9700\u8981",
    "object": "\u6bcf\u5929\u63d0\u4f9b"
  },
  {
    "subject": "\u996e\u6c34",
    "predicate": "\u9700\u8981",
    "object": "\u6bcf\u5929\u66f4\u6362"
  },
  {
    "subject": "\u98df\u7269",
    "predicate": "\u9700\u8981",
    "object": "\u6bcf\u5929\u66f4\u6362"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u662f",
    "object": "\u4e00\u79cd\u76f8\u5bf9\u72ec\u7acb\u7684\u52a8\u7269"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u559c\u6b22",
    "object": "\u72ec\u5c45"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u5bb9\u6613",
    "object": "\u53d7\u5230\u60ca\u5413"
  },
  {
    "subject": "\u9972\u517b\u4ed3\u9f20",
    "predicate": "\u9700\u8981",
    "object": "\u6ce8\u610f\u536b\u751f"
  },
  {
    "subject": "\u9972\u517b\u4ed3\u9f20",
    "predicate": "\u9700\u8981",
    "object": "\u5b9a\u671f\u6e05\u7406"
  },
  {
    "subject": "\u9972\u517b\u4ed3\u9f20",
    "predicate": "\u9700\u8981",
    "object": "\u89c2\u5bdf\u8eab\u4f53\u72b6\u51b5"
  },
  {
    "subject": "\u517b\u4ed3\u9f20",
    "predicate": "\u5e26\u6765",
    "object": "\u6109\u60a6\u611f"
  },
  {
    "subject": "\u517b\u4ed3\u9f20",
    "predicate": "\u80fd",
    "object": "\u5b66\u5230\u77e5\u8bc6"
  },
  {
    "subject": "\u517b\u4ed3\u9f20",
    "predicate": "\u6559\u80b2",
    "object": "\u4eba\u4eec"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u662f",
    "object": "\u4e00\u79cd\u53ef\u7231\u7684\u52a8\u7269"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u9002\u5408",
    "object": "\u5bb6\u5ead\u9972\u517b"
  }
]
--------------------
5. Validating structure and extracting triples...
   Found 31 valid triples in this chunk.
--- Valid Triples Extracted (Chunk 6) ---

   subject predicate     object  chunk
0       仓鼠         吃         坚果      6
1       仓鼠         吃         谷物      6
2       仓鼠         吃         昆虫      6
3       仓鼠         吃       小型动物      6
4       仓鼠        储存         食物      6
5       仓鼠        储存         食物      6
6       仓鼠        具备      将食物储存      6
7       仓鼠        具备      将食物储存      6
8       仓鼠        塞满         颊囊      6
9       仓鼠        带回         巢穴      6
10      仓鼠        需要       足够空间      6
11      笼子         应       足够宽敞      6
12      笼子        配备         跑轮      6
13      笼子        配备         隧道      6
14      笼子        配备         木屋      6
15      笼子        配备         玩具      6
16      饮水        需要       每天提供      6
17      食物        需要       每天提供      6
18      饮水        需要       每天更换      6
19      食物        需要       每天更换      6
20      仓鼠         是  一种相对独立的动物      6
21      仓鼠        喜欢         独居      6
22      仓鼠        容易       受到惊吓      6
23    饲养仓鼠        需要       注意卫生      6
24    饲养仓鼠        需要       定期清理      6
25    饲养仓鼠        需要     观察身体状况      6
26     养仓鼠        带来        愉悦感      6
27     养仓鼠         能       学到知识      6
28     养仓鼠        教育         人们      6
29      仓鼠         是    一种可爱的动物      6
30      仓鼠        适合       家庭饲养      6

--------------------
--- Running Total Triples Extracted: 136 ---
--- Failed Chunks So Far: 0 ---

--- Processing Chunk 7/10 ---
1. Formatting User Prompt...
2. Sending request to LLM...
   LLM response received.
3. Extracting raw response content...
--- Raw LLM Output (Chunk {chunk_num}) ---
[{"subject": "照料小动物", "predicate": "需要", "object": "长期承诺"}, {"subject": "仓鼠", "predicate": "是", "object": "可爱动物"}, {"subject": "仓鼠", "predicate": "适合", "object": "家庭饲养"}, {"subject": "猫头鹰", "predicate": "是", "object": "夜行性猛禽"}, {"subject": "猫头鹰", "predicate": "具有", "object": "高视觉和听觉能力"}, {"subject": "猫头鹰", "predicate": "可以旋转", "object": "头部约270度"}, {"subject": "猫头鹰", "predicate": "被视为", "object": "智慧象征"}, {"subject": "鹦鹉", "predicate": "是", "object": "美丽聪明鸟类"}, {"subject": "鹦鹉", "predicate": "能够模仿", "object": "人类语言和声音"}, {"subject": "鹦鹉", "predicate": "具有", "object": "鲜艳羽毛"}, {"subject": "鹦鹉", "predicate": "以", "object": "种子坚果和水果为食"}, {"subject": "鹦鹉", "predicate": "是", "object": "群居动物"}, {"subject": "鹦鹉", "predicate": "生活在", "object": "热带和亚热带地区森林"}, {"subject": "鹦鹉", "predicate": "是", "object": "人类宠物"}, {"subject": "狼", "predicate": "是", "object": "极具智慧和社会性动物"}, {"subject": "狼", "predicate": "属于", "object": "犬科"}]
--------------------
4. Attempting to parse JSON from response...
   Successfully parsed JSON list directly.
--- Parsed JSON Data (Chunk {chunk_num}) ---
[
  {
    "subject": "\u7167\u6599\u5c0f\u52a8\u7269",
    "predicate": "\u9700\u8981",
    "object": "\u957f\u671f\u627f\u8bfa"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u662f",
    "object": "\u53ef\u7231\u52a8\u7269"
  },
  {
    "subject": "\u4ed3\u9f20",
    "predicate": "\u9002\u5408",
    "object": "\u5bb6\u5ead\u9972\u517b"
  },
  {
    "subject": "\u732b\u5934\u9e70",
    "predicate": "\u662f",
    "object": "\u591c\u884c\u6027\u731b\u79bd"
  },
  {
    "subject": "\u732b\u5934\u9e70",
    "predicate": "\u5177\u6709",
    "object": "\u9ad8\u89c6\u89c9\u548c\u542c\u89c9\u80fd\u529b"
  },
  {
    "subject": "\u732b\u5934\u9e70",
    "predicate": "\u53ef\u4ee5\u65cb\u8f6c",
    "object": "\u5934\u90e8\u7ea6270\u5ea6"
  },
  {
    "subject": "\u732b\u5934\u9e70",
    "predicate": "\u88ab\u89c6\u4e3a",
    "object": "\u667a\u6167\u8c61\u5f81"
  },
  {
    "subject": "\u9e66\u9e49",
    "predicate": "\u662f",
    "object": "\u7f8e\u4e3d\u806a\u660e\u9e1f\u7c7b"
  },
  {
    "subject": "\u9e66\u9e49",
    "predicate": "\u80fd\u591f\u6a21\u4eff",
    "object": "\u4eba\u7c7b\u8bed\u8a00\u548c\u58f0\u97f3"
  },
  {
    "subject": "\u9e66\u9e49",
    "predicate": "\u5177\u6709",
    "object": "\u9c9c\u8273\u7fbd\u6bdb"
  },
  {
    "subject": "\u9e66\u9e49",
    "predicate": "\u4ee5",
    "object": "\u79cd\u5b50\u575a\u679c\u548c\u6c34\u679c\u4e3a\u98df"
  },
  {
    "subject": "\u9e66\u9e49",
    "predicate": "\u662f",
    "object": "\u7fa4\u5c45\u52a8\u7269"
  },
  {
    "subject": "\u9e66\u9e49",
    "predicate": "\u751f\u6d3b\u5728",
    "object": "\u70ed\u5e26\u548c\u4e9a\u70ed\u5e26\u5730\u533a\u68ee\u6797"
  },
  {
    "subject": "\u9e66\u9e49",
    "predicate": "\u662f",
    "object": "\u4eba\u7c7b\u5ba0\u7269"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u662f",
    "object": "\u6781\u5177\u667a\u6167\u548c\u793e\u4f1a\u6027\u52a8\u7269"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u5c5e\u4e8e",
    "object": "\u72ac\u79d1"
  }
]
--------------------
5. Validating structure and extracting triples...
   Found 16 valid triples in this chunk.
--- Valid Triples Extracted (Chunk 7) ---

   subject predicate      object  chunk
0    照料小动物        需要        长期承诺      7
1       仓鼠         是        可爱动物      7
2       仓鼠        适合        家庭饲养      7
3      猫头鹰         是       夜行性猛禽      7
4      猫头鹰        具有    高视觉和听觉能力      7
5      猫头鹰      可以旋转     头部约270度      7
6      猫头鹰       被视为        智慧象征      7
7       鹦鹉         是      美丽聪明鸟类      7
8       鹦鹉      能够模仿     人类语言和声音      7
9       鹦鹉        具有        鲜艳羽毛      7
10      鹦鹉         以   种子坚果和水果为食      7
11      鹦鹉         是        群居动物      7
12      鹦鹉       生活在  热带和亚热带地区森林      7
13      鹦鹉         是        人类宠物      7
14       狼         是  极具智慧和社会性动物      7
15       狼        属于          犬科      7

--------------------
--- Running Total Triples Extracted: 152 ---
--- Failed Chunks So Far: 0 ---

--- Processing Chunk 8/10 ---
1. Formatting User Prompt...
2. Sending request to LLM...
   LLM response received.
3. Extracting raw response content...
--- Raw LLM Output (Chunk {chunk_num}) ---
[{"subject": "狼", "predicate": "属于", "object": "犬科"}, {"subject": "狼", "predicate": "是", "object": "野生哺乳动物"}, {"subject": "狼", "predicate": "生活在", "object": "群体"}, {"subject": "狼", "predicate": "进行", "object": "猎食"}, {"subject": "狼群", "predicate": "组成", "object": "核心家庭"}, {"subject": "狼群", "predicate": "有", "object": "等级制度"}, {"subject": "狼", "predicate": "扮演", "object": "重要角色"}, {"subject": "狼", "predicate": "是", "object": "顶级捕食者"}, {"subject": "狼", "predicate": "猎食", "object": "草食性动物"}, {"subject": "狼", "predicate": "帮助控制", "object": "猎物数量"}, {"subject": "狼", "predicate": "维持", "object": "生态系统平衡"}, {"subject": "狼", "predicate": "以", "object": "敏锐的感官和强大的追踪能力闻名"}, {"subject": "狼", "predicate": "有", "object": "卓越的听觉和嗅觉"}, {"subject": "狼", "predicate": "进行", "object": "沟通"}, {"subject": "狼", "predicate": "使用", "object": "嚎叫"}, {"subject": "狼嚎叫", "predicate": "用于", "object": "标识领地"}, {"subject": "狼嚎叫", "predicate": "用于", "object": "召唤同伴"}, {"subject": "狼嚎叫", "predicate": "用于", "object": "警告敌人"}, {"subject": "狼", "predicate": "使用", "object": "肢体语言"}, {"subject": "狼", "predicate": "使用", "object": "面部表情"}, {"subject": "狼", "predicate": "使用", "object": "气味"}, {"subject": "狼", "predicate": "繁殖", "object": "一次"}, {"subject": "狼群", "predicate": "允许", "object": "一个主导的交配对进行繁殖"}]
--------------------
4. Attempting to parse JSON from response...
   Successfully parsed JSON list directly.
--- Parsed JSON Data (Chunk {chunk_num}) ---
[
  {
    "subject": "\u72fc",
    "predicate": "\u5c5e\u4e8e",
    "object": "\u72ac\u79d1"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u662f",
    "object": "\u91ce\u751f\u54fa\u4e73\u52a8\u7269"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u751f\u6d3b\u5728",
    "object": "\u7fa4\u4f53"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u8fdb\u884c",
    "object": "\u730e\u98df"
  },
  {
    "subject": "\u72fc\u7fa4",
    "predicate": "\u7ec4\u6210",
    "object": "\u6838\u5fc3\u5bb6\u5ead"
  },
  {
    "subject": "\u72fc\u7fa4",
    "predicate": "\u6709",
    "object": "\u7b49\u7ea7\u5236\u5ea6"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u626e\u6f14",
    "object": "\u91cd\u8981\u89d2\u8272"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u662f",
    "object": "\u9876\u7ea7\u6355\u98df\u8005"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u730e\u98df",
    "object": "\u8349\u98df\u6027\u52a8\u7269"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u5e2e\u52a9\u63a7\u5236",
    "object": "\u730e\u7269\u6570\u91cf"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u7ef4\u6301",
    "object": "\u751f\u6001\u7cfb\u7edf\u5e73\u8861"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u4ee5",
    "object": "\u654f\u9510\u7684\u611f\u5b98\u548c\u5f3a\u5927\u7684\u8ffd\u8e2a\u80fd\u529b\u95fb\u540d"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u6709",
    "object": "\u5353\u8d8a\u7684\u542c\u89c9\u548c\u55c5\u89c9"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u8fdb\u884c",
    "object": "\u6c9f\u901a"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u4f7f\u7528",
    "object": "\u568e\u53eb"
  },
  {
    "subject": "\u72fc\u568e\u53eb",
    "predicate": "\u7528\u4e8e",
    "object": "\u6807\u8bc6\u9886\u5730"
  },
  {
    "subject": "\u72fc\u568e\u53eb",
    "predicate": "\u7528\u4e8e",
    "object": "\u53ec\u5524\u540c\u4f34"
  },
  {
    "subject": "\u72fc\u568e\u53eb",
    "predicate": "\u7528\u4e8e",
    "object": "\u8b66\u544a\u654c\u4eba"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u4f7f\u7528",
    "object": "\u80a2\u4f53\u8bed\u8a00"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u4f7f\u7528",
    "object": "\u9762\u90e8\u8868\u60c5"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u4f7f\u7528",
    "object": "\u6c14\u5473"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u7e41\u6b96",
    "object": "\u4e00\u6b21"
  },
  {
    "subject": "\u72fc\u7fa4",
    "predicate": "\u5141\u8bb8",
    "object": "\u4e00\u4e2a\u4e3b\u5bfc\u7684\u4ea4\u914d\u5bf9\u8fdb\u884c\u7e41\u6b96"
  }
]
--------------------
5. Validating structure and extracting triples...
   Found 23 valid triples in this chunk.
--- Valid Triples Extracted (Chunk 8) ---

   subject predicate           object  chunk
0        狼        属于               犬科      8
1        狼         是           野生哺乳动物      8
2        狼       生活在               群体      8
3        狼        进行               猎食      8
4       狼群        组成             核心家庭      8
5       狼群         有             等级制度      8
6        狼        扮演             重要角色      8
7        狼         是            顶级捕食者      8
8        狼        猎食            草食性动物      8
9        狼      帮助控制             猎物数量      8
10       狼        维持           生态系统平衡      8
11       狼         以  敏锐的感官和强大的追踪能力闻名      8
12       狼         有         卓越的听觉和嗅觉      8
13       狼        进行               沟通      8
14       狼        使用               嚎叫      8
15     狼嚎叫        用于             标识领地      8
16     狼嚎叫        用于             召唤同伴      8
17     狼嚎叫        用于             警告敌人      8
18       狼        使用             肢体语言      8
19       狼        使用             面部表情      8
20       狼        使用               气味      8
21       狼        繁殖               一次      8
22      狼群        允许     一个主导的交配对进行繁殖      8

--------------------
--- Running Total Triples Extracted: 175 ---
--- Failed Chunks So Far: 0 ---

--- Processing Chunk 9/10 ---
1. Formatting User Prompt...
2. Sending request to LLM...
   LLM response received.
3. Extracting raw response content...
--- Raw LLM Output (Chunk {chunk_num}) ---
[{"subject": "狼群", "predicate": "允许", "object": "一个主导的交配对进行繁殖"}, {"subject": "整个狼群", "predicate": "参与", "object": "照料和保护幼狼"}, {"subject": "幼狼", "predicate": "跟随", "object": "成年狼一起猎食"}, {"subject": "人类活动", "predicate": "导致", "object": "狼的生存环境面临诸多挑战"}, {"subject": "人类", "predicate": "猎杀", "object": "狼"}, {"subject": "栖息地", "predicate": "破坏", "object": "狼"}, {"subject": "保护意识", "predicate": "增强", "object": "狼的数量"}, {"subject": "生态保护措施", "predicate": "实施", "object": "狼的数量"}, {"subject": "狼", "predicate": "被视为", "object": "勇敢和自由的象征"}, {"subject": "狼", "predicate": "被视为", "object": "危险和狡猾的化身"}, {"subject": "狼", "predicate": "用于", "object": "研究有关行为学和群体动力学"}, {"subject": "狼", "predicate": "扮演", "object": "重要角色"}, {"subject": "狼", "predicate": "发挥", "object": "关键作用"}]
--------------------
4. Attempting to parse JSON from response...
   Successfully parsed JSON list directly.
--- Parsed JSON Data (Chunk {chunk_num}) ---
[
  {
    "subject": "\u72fc\u7fa4",
    "predicate": "\u5141\u8bb8",
    "object": "\u4e00\u4e2a\u4e3b\u5bfc\u7684\u4ea4\u914d\u5bf9\u8fdb\u884c\u7e41\u6b96"
  },
  {
    "subject": "\u6574\u4e2a\u72fc\u7fa4",
    "predicate": "\u53c2\u4e0e",
    "object": "\u7167\u6599\u548c\u4fdd\u62a4\u5e7c\u72fc"
  },
  {
    "subject": "\u5e7c\u72fc",
    "predicate": "\u8ddf\u968f",
    "object": "\u6210\u5e74\u72fc\u4e00\u8d77\u730e\u98df"
  },
  {
    "subject": "\u4eba\u7c7b\u6d3b\u52a8",
    "predicate": "\u5bfc\u81f4",
    "object": "\u72fc\u7684\u751f\u5b58\u73af\u5883\u9762\u4e34\u8bf8\u591a\u6311\u6218"
  },
  {
    "subject": "\u4eba\u7c7b",
    "predicate": "\u730e\u6740",
    "object": "\u72fc"
  },
  {
    "subject": "\u6816\u606f\u5730",
    "predicate": "\u7834\u574f",
    "object": "\u72fc"
  },
  {
    "subject": "\u4fdd\u62a4\u610f\u8bc6",
    "predicate": "\u589e\u5f3a",
    "object": "\u72fc\u7684\u6570\u91cf"
  },
  {
    "subject": "\u751f\u6001\u4fdd\u62a4\u63aa\u65bd",
    "predicate": "\u5b9e\u65bd",
    "object": "\u72fc\u7684\u6570\u91cf"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u88ab\u89c6\u4e3a",
    "object": "\u52c7\u6562\u548c\u81ea\u7531\u7684\u8c61\u5f81"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u88ab\u89c6\u4e3a",
    "object": "\u5371\u9669\u548c\u72e1\u733e\u7684\u5316\u8eab"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u7528\u4e8e",
    "object": "\u7814\u7a76\u6709\u5173\u884c\u4e3a\u5b66\u548c\u7fa4\u4f53\u52a8\u529b\u5b66"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u626e\u6f14",
    "object": "\u91cd\u8981\u89d2\u8272"
  },
  {
    "subject": "\u72fc",
    "predicate": "\u53d1\u6325",
    "object": "\u5173\u952e\u4f5c\u7528"
  }
]
--------------------
5. Validating structure and extracting triples...
   Found 13 valid triples in this chunk.
--- Valid Triples Extracted (Chunk 9) ---

   subject predicate         object  chunk
0       狼群        允许   一个主导的交配对进行繁殖      9
1     整个狼群        参与        照料和保护幼狼      9
2       幼狼        跟随        成年狼一起猎食      9
3     人类活动        导致   狼的生存环境面临诸多挑战      9
4       人类        猎杀              狼      9
5      栖息地        破坏              狼      9
6     保护意识        增强           狼的数量      9
7   生态保护措施        实施           狼的数量      9
8        狼       被视为       勇敢和自由的象征      9
9        狼       被视为       危险和狡猾的化身      9
10       狼        用于  研究有关行为学和群体动力学      9
11       狼        扮演           重要角色      9
12       狼        发挥           关键作用      9

--------------------
--- Running Total Triples Extracted: 188 ---
--- Failed Chunks So Far: 0 ---

--- Processing Chunk 10/10 ---
1. Formatting User Prompt...
2. Sending request to LLM...
   LLM response received.
3. Extracting raw response content...
--- Raw LLM Output (Chunk {chunk_num}) ---
[{"subject": "保护狼以及它们的栖息地", "predicate": "变得", "object": "尤为重要"}, {"subject": "保护狼以及它们的栖息地", "predicate": "能维持", "object": "生态系统健康发展"}, {"subject": "保护狼以及它们的栖息地", "predicate": "能确保", "object": "自然界中这种神秘而迷人的动物能够继续发挥其作用"}]
--------------------
4. Attempting to parse JSON from response...
   Successfully parsed JSON list directly.
--- Parsed JSON Data (Chunk {chunk_num}) ---
[
  {
    "subject": "\u4fdd\u62a4\u72fc\u4ee5\u53ca\u5b83\u4eec\u7684\u6816\u606f\u5730",
    "predicate": "\u53d8\u5f97",
    "object": "\u5c24\u4e3a\u91cd\u8981"
  },
  {
    "subject": "\u4fdd\u62a4\u72fc\u4ee5\u53ca\u5b83\u4eec\u7684\u6816\u606f\u5730",
    "predicate": "\u80fd\u7ef4\u6301",
    "object": "\u751f\u6001\u7cfb\u7edf\u5065\u5eb7\u53d1\u5c55"
  },
  {
    "subject": "\u4fdd\u62a4\u72fc\u4ee5\u53ca\u5b83\u4eec\u7684\u6816\u606f\u5730",
    "predicate": "\u80fd\u786e\u4fdd",
    "object": "\u81ea\u7136\u754c\u4e2d\u8fd9\u79cd\u795e\u79d8\u800c\u8ff7\u4eba\u7684\u52a8\u7269\u80fd\u591f\u7ee7\u7eed\u53d1\u6325\u5176\u4f5c\u7528"
  }
]
--------------------
5. Validating structure and extracting triples...
   Found 3 valid triples in this chunk.
--- Valid Triples Extracted (Chunk 10) ---

       subject predicate                   object  chunk
0  保护狼以及它们的栖息地        变得                     尤为重要     10
1  保护狼以及它们的栖息地       能维持                 生态系统健康发展     10
2  保护狼以及它们的栖息地       能确保  自然界中这种神秘而迷人的动物能够继续发挥其作用     10

--------------------
--- Running Total Triples Extracted: 191 ---
--- Failed Chunks So Far: 0 ---

Finished processing this chunk.

### Extraction Summary (After Processing All Chunks)

**(Note:** The previous cell only processed *one* chunk for demonstration. In a full run, the loop would process all chunks. The summary below reflects the state *after* the demonstrated single chunk processing. Run the full loop from the original notebook to get the complete results).**

Let's summarize the extraction results and display all accumulated triples.

In [47]:
# --- Summary of Extraction (Reflecting state after the single chunk demo) ---
print("\n--- Overall Extraction Summary ---")
print(f"Total chunks defined: {len(chunks)}")
processed_chunks = len(chunks) - len(
    failed_chunks
)  # Approximation if loop isn't run fully
print(
    f"Chunks processed (attempted): {processed_chunks + len(failed_chunks)}"
)  # Chunks we looped through
print(
    f"Total valid triples extracted across all processed chunks: {len(all_extracted_triples)}"
)
print(f"Number of chunks that failed API call or parsing: {len(failed_chunks)}")

if failed_chunks:
    print("\nDetails of Failed Chunks:")
    for failure in failed_chunks:
        print(f"  Chunk {failure['chunk_number']}: Error: {failure['error']}")
        # print(f"    Response (start): {failure.get('response', '')[:100]}...") # Uncomment for more detail
print("-" * 25)

# Display all extracted triples using Pandas
print("\n--- All Extracted Triples (Before Normalization) ---")
if all_extracted_triples:
    all_triples_df = pd.DataFrame(all_extracted_triples)
    display(all_triples_df)
else:
    print("No triples were successfully extracted.")
print("-" * 25)

--- Overall Extraction Summary ---
Total chunks defined: 10
Chunks processed (attempted): 10
Total valid triples extracted across all processed chunks: 191
Number of chunks that failed API call or parsing: 0
-------------------------

--- All Extracted Triples (Before Normalization) ---

         subject predicate                   object  chunk
0             动物         是          地球上生物多样性的重要组成部分      1
1             动物         与        植物、微生物共同构成复杂的生态系统      1
2             动物       维持着                  地球的生态平衡      1
3             动物         是                    大自然奇迹      1
4         地球上的动物        种类                       繁多      1
..           ...       ...                      ...    ...
186            狼        扮演                     重要角色      9
187            狼        发挥                     关键作用      9
188  保护狼以及它们的栖息地        变得                     尤为重要     10
189  保护狼以及它们的栖息地       能维持                 生态系统健康发展     10
190  保护狼以及它们的栖息地       能确保  自然界中这种神秘而迷人的动物能够继续发挥其作用     10

[191 rows x 4 columns]

-------------------------

## Step 8: Normalize and De-duplicate Triples

Now, we clean up the extracted triples:
1.  **Normalize:** Trim whitespace, convert to lowercase.
2.  **Filter:** Remove triples with empty parts after normalization.
3.  **De-duplicate:** Remove exact duplicate `(subject, predicate, object)` combinations.

In [48]:
# Initialize lists and tracking variables
normalized_triples = []
seen_triples = set()  # Tracks (subject, predicate, object) tuples
original_count = len(all_extracted_triples)
empty_removed_count = 0
duplicates_removed_count = 0

print(f"Starting normalization and de-duplication of {original_count} triples...")

Starting normalization and de-duplication of 191 triples...

We'll iterate through the extracted triples, clean them, and check for duplicates. We'll show the first few transformations.

In [49]:
print("Processing triples for normalization (showing first 5 examples):")
example_limit = 5
processed_count = 0

for i, triple in enumerate(all_extracted_triples):
    show_example = i < example_limit
    if show_example:
        print(f"\n--- Example {i + 1} ---")
        print(f"Original Triple (Chunk {triple.get('chunk', '?')}): {triple}")

    subject_raw = triple.get("subject")
    predicate_raw = triple.get("predicate")
    object_raw = triple.get("object")
    chunk_num = triple.get("chunk", "unknown")

    triple_valid = False
    normalized_sub, normalized_pred, normalized_obj = None, None, None

    if (
        isinstance(subject_raw, str)
        and isinstance(predicate_raw, str)
        and isinstance(object_raw, str)
    ):
        # 1. Normalize
        normalized_sub = subject_raw.strip().lower()
        normalized_pred = re.sub(r"\s+", " ", predicate_raw.strip().lower()).strip()
        normalized_obj = object_raw.strip().lower()
        if show_example:
            print(
                f"Normalized: SUB='{normalized_sub}', PRED='{normalized_pred}', OBJ='{normalized_obj}'"
            )

        # 2. Filter Empty
        if normalized_sub and normalized_pred and normalized_obj:
            triple_identifier = (normalized_sub, normalized_pred, normalized_obj)

            # 3. De-duplicate
            if triple_identifier not in seen_triples:
                normalized_triples.append(
                    {
                        "subject": normalized_sub,
                        "predicate": normalized_pred,
                        "object": normalized_obj,
                        "source_chunk": chunk_num,
                    }
                )
                seen_triples.add(triple_identifier)
                triple_valid = True
                if show_example:
                    print("Status: Kept (New Unique Triple)")
            else:
                duplicates_removed_count += 1
                if show_example:
                    print("Status: Discarded (Duplicate)")
        else:
            empty_removed_count += 1
            if show_example:
                print("Status: Discarded (Empty component after normalization)")
    else:
        empty_removed_count += 1  # Count non-string/missing as needing removal
        if show_example:
            print("Status: Discarded (Non-string or missing component)")
    processed_count += 1

print(f"\n... Finished processing {processed_count} triples.")

Processing triples for normalization (showing first 5 examples):

--- Example 1 ---
Original Triple (Chunk 1): {'subject': '动物', 'predicate': '是', 'object': '地球上生物多样性的重要组成部分', 'chunk': 1}
Normalized: SUB='动物', PRED='是', OBJ='地球上生物多样性的重要组成部分'
Status: Kept (New Unique Triple)

--- Example 2 ---
Original Triple (Chunk 1): {'subject': '动物', 'predicate': '与', 'object': '植物、微生物共同构成复杂的生态系统', 'chunk': 1}
Normalized: SUB='动物', PRED='与', OBJ='植物、微生物共同构成复杂的生态系统'
Status: Kept (New Unique Triple)

--- Example 3 ---
Original Triple (Chunk 1): {'subject': '动物', 'predicate': '维持着', 'object': '地球的生态平衡', 'chunk': 1}
Normalized: SUB='动物', PRED='维持着', OBJ='地球的生态平衡'
Status: Kept (New Unique Triple)

--- Example 4 ---
Original Triple (Chunk 1): {'subject': '动物', 'predicate': '是', 'object': '大自然奇迹', 'chunk': 1}
Normalized: SUB='动物', PRED='是', OBJ='大自然奇迹'
Status: Kept (New Unique Triple)

--- Example 5 ---
Original Triple (Chunk 1): {'subject': '地球上的动物', 'predicate': '种类', 'object': '繁多', 'chunk': 1}
Normalized: SUB='地球上的动物', PRED='种类', OBJ='繁多'
Status: Kept (New Unique Triple)

... Finished processing 191 triples.

Let's summarize the normalization results and display the final list of unique, clean triples.

In [50]:
# --- Summary of Normalization ---
print("\n--- Normalization & De-duplication Summary ---")
print(f"Original extracted triple count: {original_count}")
print(f"Triples removed (empty/invalid components): {empty_removed_count}")
print(f"Duplicate triples removed: {duplicates_removed_count}")
final_count = len(normalized_triples)
print(f"Final unique, normalized triple count: {final_count}")
print("-" * 25)

# Display a sample of normalized triples using Pandas
print("\n--- Final Normalized Triples ---")
if normalized_triples:
    normalized_df = pd.DataFrame(normalized_triples)
    display(normalized_df)
else:
    print("No valid triples remain after normalization.")
print("-" * 25)

--- Normalization & De-duplication Summary ---
Original extracted triple count: 191
Triples removed (empty/invalid components): 0
Duplicate triples removed: 9
Final unique, normalized triple count: 182
-------------------------

--- Final Normalized Triples ---

         subject predicate                   object  source_chunk
0             动物         是          地球上生物多样性的重要组成部分             1
1             动物         与        植物、微生物共同构成复杂的生态系统             1
2             动物       维持着                  地球的生态平衡             1
3             动物         是                    大自然奇迹             1
4         地球上的动物        种类                       繁多             1
..           ...       ...                      ...           ...
177            狼        用于            研究有关行为学和群体动力学             9
178            狼        发挥                     关键作用             9
179  保护狼以及它们的栖息地        变得                     尤为重要            10
180  保护狼以及它们的栖息地       能维持                 生态系统健康发展            10
181  保护狼以及它们的栖息地       能确保  自然界中这种神秘而迷人的动物能够继续发挥其作用            10

[182 rows x 4 columns]

-------------------------

## Step 9: Build the Knowledge Graph with NetworkX

Using the clean `normalized_triples`, we construct a `networkx` directed graph (`DiGraph`).
*   Subjects and Objects become nodes.
*   Predicates become edge labels.

In [51]:
# Create an empty directed graph
knowledge_graph = nx.DiGraph()

print("Initialized an empty NetworkX DiGraph.")
# Visualize the initial empty graph state
print("--- Initial Graph Info ---")
try:
    # Try the newer method first
    print(nx.info(knowledge_graph))
except AttributeError:
    # Fallback for different NetworkX versions
    print(f"Type: {type(knowledge_graph).__name__}")
    print(f"Number of nodes: {knowledge_graph.number_of_nodes()}")
    print(f"Number of edges: {knowledge_graph.number_of_edges()}")
print("-" * 25)

Initialized an empty NetworkX DiGraph.
--- Initial Graph Info ---
Type: DiGraph
Number of nodes: 0
Number of edges: 0
-------------------------

Now, we add the triples to the graph one by one, showing the graph's growth.

In [52]:
print("Adding triples to the NetworkX graph...")

added_edges_count = 0
update_interval = 5  # How often to print graph info update

if not normalized_triples:
    print("Warning: No normalized triples to add to the graph.")
else:
    for i, triple in enumerate(normalized_triples):
        subject_node = triple["subject"]
        object_node = triple["object"]
        predicate_label = triple["predicate"]

        # Nodes are added automatically when adding edges, but explicit calls are fine too
        # knowledge_graph.add_node(subject_node)
        # knowledge_graph.add_node(object_node)

        # Add the directed edge with the predicate as a 'label' attribute
        knowledge_graph.add_edge(subject_node, object_node, label=predicate_label)
        added_edges_count += 1

        # --- Visualize Graph Growth ---
        if (i + 1) % update_interval == 0 or (i + 1) == len(normalized_triples):
            print(
                f"\n--- Graph Info after adding Triple #{i + 1} --- ({subject_node} -> {object_node})"
            )
            try:
                # Try the newer method first
                print(nx.info(knowledge_graph))
            except AttributeError:
                # Fallback for different NetworkX versions
                print(f"Type: {type(knowledge_graph).__name__}")
                print(f"Number of nodes: {knowledge_graph.number_of_nodes()}")
                print(f"Number of edges: {knowledge_graph.number_of_edges()}")
            # For very large graphs, printing info too often can be slow. Adjust interval.

print(f"\nFinished adding triples. Processed {added_edges_count} edges.")

Adding triples to the NetworkX graph...

--- Graph Info after adding Triple #5 --- (地球上的动物 -> 繁多)
Type: DiGraph
Number of nodes: 7
Number of edges: 5

--- Graph Info after adding Triple #10 --- (很多动物 -> 朋友、助手或工作伙伴的角色)
Type: DiGraph
Number of nodes: 16
Number of edges: 10

--- Graph Info after adding Triple #15 --- (实验动物 -> 科学研究的重要对象)
Type: DiGraph
Number of nodes: 25
Number of edges: 15

--- Graph Info after adding Triple #20 --- (偷猎和非法贸易 -> 某些物种的生存危机)
Type: DiGraph
Number of nodes: 33
Number of edges: 19

--- Graph Info after adding Triple #25 --- (动物 -> 自然界的珍宝)
Type: DiGraph
Number of nodes: 40
Number of edges: 24

--- Graph Info after adding Triple #30 --- (猫 -> 温顺和独立性)
Type: DiGraph
Number of nodes: 47
Number of edges: 29

--- Graph Info after adding Triple #35 --- (猫的呼噜声 -> 舒缓和疗愈作用)
Type: DiGraph
Number of nodes: 53
Number of edges: 34

--- Graph Info after adding Triple #40 --- (狗 -> 各种工作)
Type: DiGraph
Number of nodes: 59
Number of edges: 39

--- Graph Info after adding Triple #45 --- (狐狸 -> 尖尖的鼻子和耳朵)
Type: DiGraph
Number of nodes: 65
Number of edges: 44

--- Graph Info after adding Triple #50 --- (狐狸 -> 自己的领地)
Type: DiGraph
Number of nodes: 70
Number of edges: 49

--- Graph Info after adding Triple #55 --- (狐狸 -> 智谋)
Type: DiGraph
Number of nodes: 76
Number of edges: 54

--- Graph Info after adding Triple #60 --- (狐狸 -> 食物链一部分)
Type: DiGraph
Number of nodes: 80
Number of edges: 59

--- Graph Info after adding Triple #65 --- (狐狸 -> 保护生态平衡重要对象)
Type: DiGraph
Number of nodes: 88
Number of edges: 64

--- Graph Info after adding Triple #70 --- (狐狸 -> 自然界的精灵)
Type: DiGraph
Number of nodes: 94
Number of edges: 69

--- Graph Info after adding Triple #75 --- (狐狸的故事和传说 -> 人类文化一部分)
Type: DiGraph
Number of nodes: 99
Number of edges: 73

--- Graph Info after adding Triple #80 --- (仓鼠 -> 人们喜爱)
Type: DiGraph
Number of nodes: 106
Number of edges: 78

--- Graph Info after adding Triple #85 --- (每种仓鼠 -> 自己独特特征)
Type: DiGraph
Number of nodes: 114
Number of edges: 83

--- Graph Info after adding Triple #90 --- (仓鼠 -> 各种环境)
Type: DiGraph
Number of nodes: 121
Number of edges: 88

--- Graph Info after adding Triple #95 --- (仓鼠 -> 夜行动物)
Type: DiGraph
Number of nodes: 127
Number of edges: 93

--- Graph Info after adding Triple #100 --- (仓鼠 -> 一些昆虫和小型动物)
Type: DiGraph
Number of nodes: 133
Number of edges: 98

--- Graph Info after adding Triple #105 --- (仓鼠 -> 昆虫)
Type: DiGraph
Number of nodes: 138
Number of edges: 103

--- Graph Info after adding Triple #110 --- (仓鼠 -> 巢穴)
Type: DiGraph
Number of nodes: 143
Number of edges: 108

--- Graph Info after adding Triple #115 --- (笼子 -> 木屋)
Type: DiGraph
Number of nodes: 149
Number of edges: 113

--- Graph Info after adding Triple #120 --- (食物 -> 每天更换)
Type: DiGraph
Number of nodes: 153
Number of edges: 118

--- Graph Info after adding Triple #125 --- (饲养仓鼠 -> 定期清理)
Type: DiGraph
Number of nodes: 159
Number of edges: 123

--- Graph Info after adding Triple #130 --- (仓鼠 -> 一种可爱的动物)
Type: DiGraph
Number of nodes: 165
Number of edges: 128

--- Graph Info after adding Triple #135 --- (猫头鹰 -> 高视觉和听觉能力)
Type: DiGraph
Number of nodes: 172
Number of edges: 133

--- Graph Info after adding Triple #140 --- (鹦鹉 -> 鲜艳羽毛)
Type: DiGraph
Number of nodes: 178
Number of edges: 138

--- Graph Info after adding Triple #145 --- (狼 -> 极具智慧和社会性动物)
Type: DiGraph
Number of nodes: 184
Number of edges: 143

--- Graph Info after adding Triple #150 --- (狼群 -> 核心家庭)
Type: DiGraph
Number of nodes: 190
Number of edges: 148

--- Graph Info after adding Triple #155 --- (狼 -> 猎物数量)
Type: DiGraph
Number of nodes: 194
Number of edges: 153

--- Graph Info after adding Triple #160 --- (狼 -> 嚎叫)
Type: DiGraph
Number of nodes: 199
Number of edges: 158

--- Graph Info after adding Triple #165 --- (狼 -> 面部表情)
Type: DiGraph
Number of nodes: 205
Number of edges: 163

--- Graph Info after adding Triple #170 --- (幼狼 -> 成年狼一起猎食)
Type: DiGraph
Number of nodes: 212
Number of edges: 168

--- Graph Info after adding Triple #175 --- (生态保护措施 -> 狼的数量)
Type: DiGraph
Number of nodes: 218
Number of edges: 173

--- Graph Info after adding Triple #180 --- (保护狼以及它们的栖息地 -> 尤为重要)
Type: DiGraph
Number of nodes: 224
Number of edges: 178

--- Graph Info after adding Triple #182 --- (保护狼以及它们的栖息地 -> 自然界中这种神秘而迷人的动物能够继续发挥其作用)
Type: DiGraph
Number of nodes: 226
Number of edges: 180

Finished adding triples. Processed 182 edges.

Let's look at the final graph statistics and sample nodes/edges.

In [53]:
# --- Final Graph Statistics ---
num_nodes = knowledge_graph.number_of_nodes()
num_edges = knowledge_graph.number_of_edges()

print("\n--- Final NetworkX Graph Summary ---")
print(f"Total unique nodes (entities): {num_nodes}")
print(f"Total unique edges (relationships): {num_edges}")

if num_edges != added_edges_count and isinstance(knowledge_graph, nx.DiGraph):
    print(
        f"Note: Added {added_edges_count} edges, but graph has {num_edges}. DiGraph overwrites edges with same source/target. Use MultiDiGraph if multiple edges needed."
    )

if num_nodes > 0:
    try:
        density = nx.density(knowledge_graph)
        print(f"Graph density: {density:.4f}")
        if nx.is_weakly_connected(knowledge_graph):
            print(
                "The graph is weakly connected (all nodes reachable ignoring direction)."
            )
        else:
            num_components = nx.number_weakly_connected_components(knowledge_graph)
            print(f"The graph has {num_components} weakly connected components.")
    except Exception as e:
        print(
            f"Could not calculate some graph metrics: {e}"
        )  # Handle potential errors on empty/small graphs
else:
    print("Graph is empty, cannot calculate metrics.")
print("-" * 25)

# --- Sample Nodes ---
print("\n--- Sample Nodes (First 10) ---")
if num_nodes > 0:
    nodes_sample = list(knowledge_graph.nodes())[:10]
    display(pd.DataFrame(nodes_sample, columns=["Node Sample"]))
else:
    print("Graph has no nodes.")

# --- Sample Edges ---
print("\n--- Sample Edges (First 10 with Labels) ---")
if num_edges > 0:
    edges_sample = []
    for u, v, data in list(knowledge_graph.edges(data=True))[:10]:
        edges_sample.append(
            {"Source": u, "Target": v, "Label": data.get("label", "N/A")}
        )
    display(pd.DataFrame(edges_sample))
else:
    print("Graph has no edges.")
print("-" * 25)

--- Final NetworkX Graph Summary ---
Total unique nodes (entities): 226
Total unique edges (relationships): 180
Note: Added 182 edges, but graph has 180. DiGraph overwrites edges with same source/target. Use MultiDiGraph if multiple edges needed.
Graph density: 0.0035
The graph has 47 weakly connected components.
-------------------------

--- Sample Nodes (First 10) ---

         Node Sample
0                 动物
1    地球上生物多样性的重要组成部分
2  植物、微生物共同构成复杂的生态系统
3            地球的生态平衡
4              大自然奇迹
5             地球上的动物
6                 繁多
7                 昆虫
8           地球的每一个角落
9            大象等大型动物

--- Sample Edges (First 10 with Labels) ---

   Source             Target Label
0      动物    地球上生物多样性的重要组成部分     是
1      动物  植物、微生物共同构成复杂的生态系统     与
2      动物            地球的生态平衡   维持着
3      动物              大自然奇迹     是
4      动物          人类有着密切的关系     与
5      动物      农业和科研中扮演着重要角色     在
6      动物           丰厚的历史和信仰    承载
7      动物             自然界的珍宝     是
8      动物           人类的朋友和老师     是
9  地球上的动物                 繁多    种类

-------------------------

## Step 10: Visualize the Graph Interactively with ipycytoscape

Finally, we visualize the constructed graph interactively within the notebook using `ipycytoscape`. We'll convert the `networkx` data, define styles, and display the widget.

In [54]:
print("Preparing interactive visualization...")

# --- Check Graph Validity for Visualization ---
can_visualize = False
if "knowledge_graph" not in locals() or not isinstance(knowledge_graph, nx.Graph):
    print("Error: 'knowledge_graph' not found or is not a NetworkX graph.")
elif knowledge_graph.number_of_nodes() == 0:
    print("NetworkX Graph is empty. Cannot visualize.")
else:
    print(
        f"Graph seems valid for visualization ({knowledge_graph.number_of_nodes()} nodes, {knowledge_graph.number_of_edges()} edges)."
    )
    can_visualize = True

Preparing interactive visualization...
Graph seems valid for visualization (226 nodes, 180 edges).

### 10.1 Convert NetworkX Data to Cytoscape Format

`ipycytoscape` requires nodes and edges in a specific JSON-like format (list of dictionaries).

In [55]:
cytoscape_nodes = []
cytoscape_edges = []

if can_visualize:
    print("Converting nodes...")
    # Calculate degrees for node sizing
    node_degrees = dict(knowledge_graph.degree())
    max_degree = max(node_degrees.values()) if node_degrees else 1

    for node_id in knowledge_graph.nodes():
        degree = node_degrees.get(node_id, 0)
        # Simple scaling for node size (adjust logic as needed)
        node_size = 15 + (degree / max_degree) * 50 if max_degree > 0 else 15

        cytoscape_nodes.append(
            {
                "data": {
                    "id": str(node_id),  # ID must be string
                    "label": str(node_id).replace(
                        " ", "\n"
                    ),  # Display label (wrap spaces)
                    "degree": degree,
                    "size": node_size,
                    "tooltip_text": f"Entity: {str(node_id)}\nDegree: {degree}",  # Tooltip on hover
                }
            }
        )
    print(f"Converted {len(cytoscape_nodes)} nodes.")

    print("Converting edges...")
    edge_count = 0
    for u, v, data in knowledge_graph.edges(data=True):
        edge_id = f"edge_{edge_count}"  # Unique edge ID
        predicate_label = data.get("label", "")
        cytoscape_edges.append(
            {
                "data": {
                    "id": edge_id,
                    "source": str(u),
                    "target": str(v),
                    "label": predicate_label,  # Label on edge
                    "tooltip_text": f"Relationship: {predicate_label}",  # Tooltip on hover
                }
            }
        )
        edge_count += 1
    print(f"Converted {len(cytoscape_edges)} edges.")

    # Combine into the final structure
    cytoscape_graph_data = {"nodes": cytoscape_nodes, "edges": cytoscape_edges}

    # Visualize the converted structure (first few nodes/edges)
    print("\n--- Sample Cytoscape Node Data (First 2) ---")
    print(json.dumps(cytoscape_graph_data["nodes"][:2], indent=2))
    print("\n--- Sample Cytoscape Edge Data (First 2) ---")
    print(json.dumps(cytoscape_graph_data["edges"][:2], indent=2))
    print("-" * 25)
else:
    print("Skipping data conversion as graph is not valid for visualization.")
    cytoscape_graph_data = {"nodes": [], "edges": []}

Converting nodes...
Converted 226 nodes.
Converting edges...
Converted 180 edges.

--- Sample Cytoscape Node Data (First 2) ---
[
  {
    "data": {
      "id": "\u52a8\u7269",
      "label": "\u52a8\u7269",
      "degree": 9,
      "size": 31.071428571428573,
      "tooltip_text": "Entity: \u52a8\u7269\nDegree: 9"
    }
  },
  {
    "data": {
      "id": "\u5730\u7403\u4e0a\u751f\u7269\u591a\u6837\u6027\u7684\u91cd\u8981\u7ec4\u6210\u90e8\u5206",
      "label": "\u5730\u7403\u4e0a\u751f\u7269\u591a\u6837\u6027\u7684\u91cd\u8981\u7ec4\u6210\u90e8\u5206",
      "degree": 1,
      "size": 16.785714285714285,
      "tooltip_text": "Entity: \u5730\u7403\u4e0a\u751f\u7269\u591a\u6837\u6027\u7684\u91cd\u8981\u7ec4\u6210\u90e8\u5206\nDegree: 1"
    }
  }
]

--- Sample Cytoscape Edge Data (First 2) ---
[
  {
    "data": {
      "id": "edge_0",
      "source": "\u52a8\u7269",
      "target": "\u5730\u7403\u4e0a\u751f\u7269\u591a\u6837\u6027\u7684\u91cd\u8981\u7ec4\u6210\u90e8\u5206",
      "label": "\u662f",
      "tooltip_text": "Relationship: \u662f"
    }
  },
  {
    "data": {
      "id": "edge_1",
      "source": "\u52a8\u7269",
      "target": "\u690d\u7269\u3001\u5fae\u751f\u7269\u5171\u540c\u6784\u6210\u590d\u6742\u7684\u751f\u6001\u7cfb\u7edf",
      "label": "\u4e0e",
      "tooltip_text": "Relationship: \u4e0e"
    }
  }
]
-------------------------

### 10.2 Create and Configure the Cytoscape Widget

In [56]:
if can_visualize:
    print("Creating ipycytoscape widget...")
    cyto_widget = ipycytoscape.CytoscapeWidget()
    print("Widget created.")

    print("Loading graph data into widget...")
    cyto_widget.graph.add_graph_from_json(cytoscape_graph_data, directed=True)
    print("Data loaded.")
else:
    print("Skipping widget creation.")
    cyto_widget = None

Creating ipycytoscape widget...
Widget created.
Loading graph data into widget...
Data loaded.

### 10.3 Define Visual Style

We use a CSS-like syntax to control the appearance of nodes and edges.

In [57]:
if cyto_widget:
    print("Defining enhanced colorful and interactive visual style...")
    # More vibrant and colorful styling with a modern color scheme
    visual_style = [
        {
            "selector": "node",
            "style": {
                "label": "data(label)",
                "width": "data(size)",
                "height": "data(size)",
                "background-color": "#3498db",  # Bright blue
                "background-opacity": 0.9,
                "color": "#ffffff",  # White text
                "font-size": "12px",
                "font-weight": "bold",
                "text-valign": "center",
                "text-halign": "center",
                "text-wrap": "wrap",
                "text-max-width": "100px",
                "text-outline-width": 2,
                "text-outline-color": "#2980b9",  # Matching outline
                "text-outline-opacity": 0.7,
                "border-width": 3,
                "border-color": "#1abc9c",  # Turquoise border
                "border-opacity": 0.9,
                "shape": "ellipse",
                "transition-property": "background-color, border-color, border-width, width, height",
                "transition-duration": "0.3s",
                "tooltip-text": "data(tooltip_text)",
            },
        },
        {
            "selector": "node:selected",
            "style": {
                "background-color": "#e74c3c",  # Pomegranate red
                "border-width": 4,
                "border-color": "#c0392b",
                "text-outline-color": "#e74c3c",
                "width": "data(size) * 1.2",  # Enlarge selected nodes
                "height": "data(size) * 1.2",
            },
        },
        {
            "selector": "node:hover",
            "style": {
                "background-color": "#9b59b6",  # Purple on hover
                "border-width": 4,
                "border-color": "#8e44ad",
                "cursor": "pointer",
                "z-index": 999,
            },
        },
        {
            "selector": "edge",
            "style": {
                "label": "data(label)",
                "width": 2.5,
                "curve-style": "bezier",
                "line-color": "#2ecc71",  # Green
                "line-opacity": 0.8,
                "target-arrow-color": "#27ae60",
                "target-arrow-shape": "triangle",
                "arrow-scale": 1.5,
                "font-size": "10px",
                "font-weight": "normal",
                "color": "#2c3e50",
                "text-background-opacity": 0.9,
                "text-background-color": "#ecf0f1",
                "text-background-shape": "roundrectangle",
                "text-background-padding": "3px",
                "text-rotation": "autorotate",
                "edge-text-rotation": "autorotate",
                "transition-property": "line-color, width, target-arrow-color",
                "transition-duration": "0.3s",
                "tooltip-text": "data(tooltip_text)",
            },
        },
        {
            "selector": "edge:selected",
            "style": {
                "line-color": "#f39c12",  # Yellow-orange
                "target-arrow-color": "#d35400",
                "width": 4,
                "text-background-color": "#f1c40f",
                "color": "#ffffff",  # White text
                "z-index": 998,
            },
        },
        {
            "selector": "edge:hover",
            "style": {
                "line-color": "#e67e22",  # Orange on hover
                "width": 3.5,
                "cursor": "pointer",
                "target-arrow-color": "#d35400",
                "z-index": 997,
            },
        },
        {
            "selector": ".center-node",
            "style": {
                "background-color": "#16a085",  # Teal
                "background-opacity": 1,
                "border-width": 4,
                "border-color": "#1abc9c",  # Turquoise border
                "border-opacity": 1,
            },
        },
    ]

    print("Setting enhanced visual style on widget...")
    cyto_widget.set_style(visual_style)

    # Apply a better animated layout
    cyto_widget.set_layout(
        name="cose",
        nodeRepulsion=5000,
        nodeOverlap=40,
        idealEdgeLength=120,
        edgeElasticity=200,
        nestingFactor=6,
        gravity=90,
        numIter=2500,
        animate=True,
        animationDuration=1000,
        initialTemp=300,
        coolingFactor=0.95,
    )

    # Add a special class to main nodes (Marie Curie)
    if len(cyto_widget.graph.nodes) > 0:
        main_nodes = [
            node.data["id"]
            for node in cyto_widget.graph.nodes
            if node.data.get("degree", 0) > 10
        ]

        # Create gradient styles for center nodes
        for i, node_id in enumerate(main_nodes):
            # Use vibrant colors for center nodes
            center_style = {
                "selector": f'node[id = "{node_id}"]',
                "style": {
                    "background-color": "#9b59b6",  # Purple
                    "background-opacity": 0.95,
                    "border-width": 4,
                    "border-color": "#8e44ad",  # Darker purple border
                    "border-opacity": 1,
                    "text-outline-width": 3,
                    "text-outline-color": "#8e44ad",
                    "font-size": "14px",
                },
            }
            visual_style.append(center_style)

        # Update the style with the new additions
        cyto_widget.set_style(visual_style)

    print("Enhanced colorful and interactive style applied successfully.")
else:
    print("Skipping style definition.")

Defining enhanced colorful and interactive visual style...
Setting enhanced visual style on widget...
Enhanced colorful and interactive style applied successfully.

### 10.4 Set Layout Algorithm

We choose an algorithm to automatically arrange the nodes and edges.

In [58]:
if cyto_widget:
    print("Setting layout algorithm ('cose')...")
    # cose (Compound Spring Embedder) is often good for exploring connections
    cyto_widget.set_layout(
        name="cose",
        animate=True,
        # Adjust parameters for better spacing/layout
        nodeRepulsion=4000,  # Increase repulsion
        nodeOverlap=40,  # Increase overlap avoidance
        idealEdgeLength=120,  # Slightly longer ideal edges
        edgeElasticity=150,
        nestingFactor=5,
        gravity=100,  # Increase gravity slightly
        numIter=1500,  # More iterations
        initialTemp=200,
        coolingFactor=0.95,
        minTemp=1.0,
    )
    print("Layout set. The graph will arrange itself when displayed.")
else:
    print("Skipping layout setting.")

Setting layout algorithm ('cose')...
Layout set. The graph will arrange itself when displayed.

### 10.5 Display the Interactive Graph

The final step is to render the interactive widget in the notebook output below.

In [59]:
from IPython.display import display

if cyto_widget:
    print("Displaying interactive graph widget below...")
    print(
        "Interact: Zoom (scroll), Pan (drag background), Move Nodes (drag nodes), Hover for details."
    )
else:
    print("No widget to display.")

print("\n" + "-" * 25 + "\nEnd of Visualization Step." + "\n" + "-" * 25)
display(cyto_widget)

Displaying interactive graph widget below...
Interact: Zoom (scroll), Pan (drag background), Move Nodes (drag nodes), Hover for details.

-------------------------
End of Visualization Step.
-------------------------

CytoscapeWidget(cytoscape_layout={'name': 'cose', 'nodeRepulsion': 4000, 'nodeOverlap': 40, 'idealEdgeLength':…

In [60]:
for u, v, data in list(knowledge_graph.edges(data=True)):
    print(u, v, data.get("label", "N/A"))  # Print edge labels for verification

动物 地球上生物多样性的重要组成部分 是
动物 植物、微生物共同构成复杂的生态系统 与
动物 地球的生态平衡 维持着
动物 大自然奇迹 是
动物 人类有着密切的关系 与
动物 农业和科研中扮演着重要角色 在
动物 丰厚的历史和信仰 承载
动物 自然界的珍宝 是
动物 人类的朋友和老师 是
地球上的动物 繁多 种类
昆虫 地球的每一个角落 占据了
大象等大型动物 体型和力量令人惊叹 以
每种动物 适应其生存环境的独特特征 通过进化发展出
很多动物 朋友、助手或工作伙伴的角色 扮演着
宠物 人类无尽的陪伴和情感支持 给予
一些工作动物 人类完成某些特殊任务 帮助
家畜和家禽 人类提供食物来源 为
实验动物 科学研究的重要对象 是
人类活动 动物的栖息地 威胁着
人类活动 狼的生存环境面临诸多挑战 导致
工业化进程、城市化扩张、森林砍伐 许多物种濒临灭绝 导致
偷猎和非法贸易 某些物种的生存危机 加剧
各国政府和国际组织 动物保护法律法规 加强
各国政府和国际组织 拯救濒危动物的努力 推动
许多文化 神灵的化身或图腾 视为
动物角色 人类无法用语言表达的情感和哲理 用来表现
保护动物及其生存环境 保护我们生态系统 是
保护动物及其生存环境 保护人类自身的未来 是
猫 一种常见的宠物 是
猫 温顺和独立性 闻名于
猫 柔软的毛发 有
猫 敏锐的感官 有
猫 敏捷的动作 有
猫 很好地适应各种居住环境 可以
猫的呼噜声 舒缓和疗愈作用 被认为具有
狗 人类的宠物 是
狗 人类最好的朋友之一 是
狗 陪伴 能够提供
狗 保护家庭 能够
狗 各种工作 可以进行
狗 很多品种 有
狗 重要角色 扮演
狐狸 犬科动物 属于
狐狸 聪明,狡猾 闻名
狐狸 尖尖的鼻子和耳朵 具有
狐狸 小型哺乳动物、鸟类以及昆虫为食 以
狐狸 植物果实 吃
狐狸 独居动物 是
狐狸 其他狐狸 交往
狐狸 自己的领地 建立
狐狸 善于变化和狡黠的化身 被看作
狐狸 不同角色 被赋予
狐狸 聪明形象 被刻画成
狐狸 智谋 运用
狐狸 诡计 通过
狐狸 害兽 被视为
狐狸 重要角色 扮演
狐狸 啮齿动物数量 帮助控制
狐狸 食物链一部分 成为
狐狸 生态系统重要组成部分 是
狐狸 保护生态平衡重要对象 成为
狐狸 极具适应能力的动物 是
狐狸 自然界特殊存在 成为
狐狸 具有性格化特征的动物 成为
狐狸 自然界的精灵 是
狐狸 激发人们创造灵感源泉 成为
狐狸 自然界精灵 是
母狐狸 隐蔽的巢穴 产仔
人们对狐狸的态度 随着时间推移 改变
狐狸皮 毛皮工业 被广泛使用于
野生狐狸生存状态 更大关注 得到
狐狸形象 丰富和立体 愈发
狐狸的故事和传说 流传 将继续
狐狸的故事和传说 人类文化一部分 成为
狐狸的名声和象征意义 广泛认可 得到
仓鼠 一种小型啮齿动物 是
仓鼠 仓鼠科 属于
仓鼠 娇小 体型
仓鼠 人们喜爱 深受
仓鼠 亚洲、欧洲及北美洲地区 主要分布在
仓鼠 中国、俄罗斯和哈萨克斯坦等地 较为常见于
仓鼠 各种环境 生活在
仓鼠 在野外生存 可以
仓鼠 人工饲养环境 能够适应
仓鼠 夜行动物 是
仓鼠 躲在洞穴 白天
仓鼠 出来觅食、活动 晚上
仓鼠 一些昆虫和小型动物 偶尔吃
仓鼠 坚果 吃
仓鼠 谷物 吃
仓鼠 昆虫 吃
仓鼠 小型动物 吃
仓鼠 食物 储存
仓鼠 将食物储存 具备
仓鼠 颊囊 塞满
仓鼠 巢穴 带回
仓鼠 足够空间 需要
仓鼠 一种相对独立的动物 是
仓鼠 独居 喜欢
仓鼠 受到惊吓 容易
仓鼠 一种可爱的动物 是
仓鼠 家庭饲养 适合
仓鼠 可爱动物 是
许多人 把仓鼠作为宠物饲养 选择
最常见仓鼠 金丝熊、坎贝尔仓鼠、加卡利亚仓鼠和罗伯罗夫斯基仓鼠 包括
每种仓鼠 自己独特特征 有
金丝熊仓鼠 较大 体型
金丝熊仓鼠 温顺 性格
加卡利亚仓鼠 较小 体型
加卡利亚仓鼠 好动 活泼
野生仓鼠 沙漠、草原 通常栖息在
沙漠、草原 充足食物和庇护所 提供
仓鼠饮食 植物为主 以
仓鼠饮食 各种种子、果实、坚果、谷物 主要包括
这种饮食习惯 有效储存食物 使仓鼠能够
这种饮食习惯 食物匮乏 应对
食物 每天提供 需要
食物 每天更换 需要
笼子 足够宽敞 应
笼子 跑轮 配备
笼子 隧道 配备
笼子 木屋 配备
笼子 玩具 配备
饮水 每天提供 需要
饮水 每天更换 需要
饲养仓鼠 注意卫生 需要
饲养仓鼠 定期清理 需要
饲养仓鼠 观察身体状况 需要
养仓鼠 愉悦感 带来
养仓鼠 学到知识 能
养仓鼠 人们 教育
照料小动物 长期承诺 需要
猫头鹰 夜行性猛禽 是
猫头鹰 高视觉和听觉能力 具有
猫头鹰 头部约270度 可以旋转
猫头鹰 智慧象征 被视为
鹦鹉 美丽聪明鸟类 是
鹦鹉 人类语言和声音 能够模仿
鹦鹉 鲜艳羽毛 具有
鹦鹉 种子坚果和水果为食 以
鹦鹉 群居动物 是
鹦鹉 热带和亚热带地区森林 生活在
鹦鹉 人类宠物 是
狼 极具智慧和社会性动物 是
狼 犬科 属于
狼 野生哺乳动物 是
狼 群体 生活在
狼 猎食 进行
狼 重要角色 扮演
狼 顶级捕食者 是
狼 草食性动物 猎食
狼 猎物数量 帮助控制
狼 生态系统平衡 维持
狼 敏锐的感官和强大的追踪能力闻名 以
狼 卓越的听觉和嗅觉 有
狼 沟通 进行
狼 嚎叫 使用
狼 肢体语言 使用
狼 面部表情 使用
狼 气味 使用
狼 一次 繁殖
狼 勇敢和自由的象征 被视为
狼 危险和狡猾的化身 被视为
狼 研究有关行为学和群体动力学 用于
狼 关键作用 发挥
狼群 核心家庭 组成
狼群 等级制度 有
狼群 一个主导的交配对进行繁殖 允许
狼嚎叫 标识领地 用于
狼嚎叫 召唤同伴 用于
狼嚎叫 警告敌人 用于
整个狼群 照料和保护幼狼 参与
幼狼 成年狼一起猎食 跟随
人类 狼 猎杀
栖息地 狼 破坏
保护意识 狼的数量 增强
生态保护措施 狼的数量 实施
保护狼以及它们的栖息地 尤为重要 变得
保护狼以及它们的栖息地 生态系统健康发展 能维持
保护狼以及它们的栖息地 自然界中这种神秘而迷人的动物能够继续发挥其作用 能确保

## Step 11: Conclusion and Next Steps

We have now walked through a very granular process:
1.  Setup libraries and LLM connection.
2.  Defined and chunked input text, visualizing intermediate steps.
3.  Defined detailed prompts for the LLM.
4.  Iterated through chunks (demonstrated with one), showing raw LLM output, parsed JSON, and extracted triples for each.
5.  Aggregated, normalized, and de-duplicated triples, showing the results.
6.  Built the `networkx` graph step-by-step, showing its growth.
7.  Converted data for `ipycytoscape` and visualized the final interactive knowledge graph directly in the notebook.

This detailed breakdown should make the transformation from unstructured text to a structured, visual knowledge graph much clearer.

**Potential Improvements and Further Exploration:**
*   **Run Full Loop:** Execute the LLM extraction and normalization across *all* chunks for a complete graph.
*   **Advanced Normalization:** Implement entity linking or relationship clustering.
*   **Error Handling:** Add retries for LLM calls, better handling of persistent chunk failures.
*   **Prompt Tuning:** Experiment with different models, prompts, and parameters.
*   **Evaluation:** Assess the quality of extracted triples (Precision/Recall).
*   **Richer Visualization:** Use node types for colors/shapes, add community detection coloring, implement more interactive features using ipycytoscape callbacks.
*   **Graph Analysis:** Apply `networkx` algorithms (centrality, paths, etc.).
*   **Persistence:** Store results in a graph database (Neo4j, etc.).